{"num": 1, "fid": "L89N-K6Q", "famc_fid": [["L89N-K6J", "L89N-K6V"]], "fams_fid": [["L89N-K6Q", "LZNR-G97"]], "famc_num": [1], "fams_num": [17], "given": "John \" Jack\" Fitzgerald", "surname": "Kennedy", "gender": "M", "birtdate": "       1917", "birtplac": "Ma", "deatdate": "1963", "deatplac": "Dallas, Texas, United States", "chrdate": null, "chrplac": null, "buridate": "25 NOV 1963", "buriplac": "Arlington Nat. C,Arlington,Vaginia", "parents": ["L89N-K6J", "L89N-K6V"], "children": [["L89N-K6Q", "LZNR-G97", "L89N-KNJ"], ["L89N-K6Q", "LZNR-G97", "L89N-K6N"], ["L89N-K6Q", "LZNR-G97", "LZNR-GF4"]], "spouses": [["L89N-K6Q", "LZNR-G97", "M6XV-PSW"]]}
{"num": 2, "fid": "L89N-K6J", "famc_fid": [["L89N-K62", "L89N-K6L"]], "fams_fid": [["L89N-K6J", "LYF5-P97"], ["L89N-K6J", "L89N-K6V"], ["L89N-K6J", "LHRR-LWW"]], "famc_num": [2], "fams_num": [1, 18, 19], "given": "Joseph Patrick", "surname": "Kennedy", "gender": "M", "birtdate": "6 September 1888", "birtplac": "Boston, Suffolk, Massachusetts, United States", "deatdate": "18 November 1969", "deatplac": "Hyannis Port, Barnstable, Barnstable, Massachusetts, United States", "chrdate": "9 September 1888", "chrplac": "East Boston, Boston, Suffolk, Massachusetts, United States", "buridate": "November 1969", "buriplac": "Brookline, Norfolk, Massachusetts, United States", "parents": ["L89N-K62", "L89N-K6L"], "children": [["L89N-K6J", "LHRR-LWW", "LYFL-XPN"], ["L89N-K6J", "LYF5-P97", "LYFL-XPN"], ["L89N-K6J", "L89N-K6V", "LRF8-RKC"], ["L89N-K6J", "L89N-K6V", "L89N-K6Q"], ["L89N-K6J", "L89N-K6V", "LZNR-GPG"], ["L89N-K6J", "L89N-K6V", "LZNR-GGF"], ["L89N-K6J", "L89N-K6V", "LJL3-M17"], ["L89N-K6J", "L89N-K6V", "LRF8-G8C"], ["L89N-K6J", "L89N-K6V", "LZNR-GRZ"], ["L89N-K6J", "L89N-K6V", "LZNR-GY3"]], "spouses": [["L89N-K6J", "L89N-K6V", "M63P-9L8"], ["L89N-K6J", "LYF5-P97", "MKD6-72T"], ["L89N-K6J", "LHRR-LWW", "MKD8-D44"]]}
{"num": 3, "fid": "L89N-K6V", "famc_fid": [["LV7R-QM8", "L83V-TTZ"]], "fams_fid": [[null, "L89N-K6V"], ["L89N-K6J", "L89N-K6V"]], "famc_num": [3], "fams_num": [1, 14], "given": "Rose Elizabeth", "surname": "FitzGerald", "gender": "F", "birtdate": "22 July 1890", "birtplac": "Boston, Suffolk, Massachusetts, United States", "deatdate": "22 January 1995", "deatplac": "Hyannis Port, Barnstable, Barnstable, Massachusetts, United States", "chrdate": null, "chrplac": null, "buridate": "25 JAN 1995", "buriplac": "Holyhood Cemetery, Brookline, MA", "parents": ["LV7R-QM8", "L83V-TTZ"], "children": [["L89N-K6J", "L89N-K6V", "LRF8-RKC"], ["L89N-K6J", "L89N-K6V", "L89N-K6Q"], [null, "L89N-K6V", "LBKC-ZV5"], ["L89N-K6J", "L89N-K6V", "LZNR-GPG"], ["L89N-K6J", "L89N-K6V", "LZNR-GGF"], ["L89N-K6J", "L89N-K6V", "LJL3-M17"], ["L89N-K6J", "L89N-K6V", "LRF8-G8C"], ["L89N-K6J", "L89N-K6V", "LZNR-GRZ"], ["L89N-K6J", "L89N-K6V", "LZNR-GY3"]], "spouses": [["L89N-K6J", "L89N-K6V", "M63P-9L8"]]}
{"num": 4, "fid": "L89N-K62", "famc_fid": [["LCVQ-NGT", "L83V-TTH"]], "fams_fid": [["L89N-K62", "9JK5-L2Y"], ["L89N-K62", "L89N-K6L"], ["L89N-K62", "KGWP-YKX"]], "famc_num": [4], "fams_num": [56, 57, 2], "given": "Patrick Joseph", "surname": "Kennedy", "gender": "M", "birtdate": "14 January 1858", "birtplac": "Boston, Suffolk, Massachusetts, United States", "deatdate": "18 May 1929", "deatplac": "Boston, Suffolk, Massachusetts, United States", "chrdate": "16 Jan 1858", "chrplac": "East Boston, Suffolk Co, MA", "buridate": null, "buriplac": "Malden, Middlesex Co, MA", "parents": ["LCVQ-NGT", "L83V-TTH"], "children": [["L89N-K62", "L89N-K6L", "L89N-K6J"], ["L89N-K62", "L89N-K6L", "K8Z9-VJ6"], ["L89N-K62", "L89N-K6L", "K6MQ-7TK"], ["L89N-K62", "L89N-K6L", "K6S9-BCF"]], "spouses": [["L89N-K62", "L89N-K6L", "M63P-9LX"], ["L89N-K62", "9JK5-L2Y", "MKGR-R4S"], ["L89N-K62", "KGWP-YKX", "MKGR-RJK"]]}
{"num": 5, "fid": "L89N-K6L", "famc_fid": [["LZ38-WH7", "LZ38-WHX"]], "fams_fid": [["L89N-K62", "L89N-K6L"]], "famc_num": [7], "fams_num": [2], "given": "Mary Augusta", "surname": "Hickey", "gender": "F", "birtdate": "6 December 1857", "birtplac": "Winthrop, Suffolk, Massachusetts, United States", "deatdate": "20 May 1923", "deatplac": "Boston, Suffolk, Massachusetts, USA", "chrdate": null, "chrplac": null, "buridate": "21 MAY 1923", "buriplac": "Malden, Middlesex Co, MA", "parents": ["LZ38-WH7", "LZ38-WHX"], "children": [["L89N-K62", "L89N-K6L", "L89N-K6J"], ["L89N-K62", "L89N-K6L", "K8Z9-VJ6"], ["L89N-K62", "L89N-K6L", "K6MQ-7TK"], ["L89N-K62", "L89N-K6L", "K6S9-BCF"]], "spouses": [["L89N-K62", "L89N-K6L", "M63P-9LX"]]}
{"num": 6, "fid": "LV7R-QM8", "famc_fid": [["KCRN-GRR", "LTVL-K2F"]], "fams_fid": [["LV7R-QM8", "L83V-TTZ"]], "famc_num": [5], "fams_num": [3], "given": "John Francis", "surname": "Fitzgerald", "gender": "M", "birtdate": "11 February 1863", "birtplac": "Boston, Suffolk, Massachusetts, United States", "deatdate": "2 October 1950", "deatplac": "Boston, Suffolk, Massachusetts, United States", "chrdate": "12 Feb 1863", "chrplac": "Boston,Suffolk,Massachusetts", "buridate": "5 OCT 1950", "buriplac": "West Roxbury, Suffolk Co, MA", "parents": ["KCRN-GRR", "LTVL-K2F"], "children": [["LV7R-QM8", "L83V-TTZ", "L89N-K6V"], ["LV7R-QM8", "L83V-TTZ", "LHTZ-LKY"], ["LV7R-QM8", "L83V-TTZ", "KG83-BL5"], ["LV7R-QM8", "L83V-TTZ", "LWRR-VRV"], ["LV7R-QM8", "L83V-TTZ", "LTC6-2SD"], ["LV7R-QM8", "L83V-TTZ", "MK43-JTP"], ["LV7R-QM8", "L83V-TTZ", "LDXR-7MW"], ["LV7R-QM8", "L83V-TTZ", "9JZ6-8Z3"], ["LV7R-QM8", "L83V-TTZ", "9JG2-46T"], ["LV7R-QM8", "L83V-TTZ", "LTQX-6CK"], ["LV7R-QM8", "L83V-TTZ", "LWLT-LFR"], ["LV7R-QM8", "L83V-TTZ", "LTC6-KVZ"], ["LV7R-QM8", "L83V-TTZ", "LTC6-V7K"], ["LV7R-QM8", "L83V-TTZ", "M32B-9WM"], ["LV7R-QM8", "L83V-TTZ", "MD9D-QV4"]], "spouses": [["LV7R-QM8", "L83V-TTZ", "MNQ8-Q9L"]]}
{"num": 7, "fid": "L83V-TTZ", "famc_fid": [["MVFK-TQP", "MVFK-TWD"]], "fams_fid": [["LV7R-QM8", "L83V-TTZ"]], "famc_num": [6], "fams_num": [3], "given": "Mary Josephine", "surname": "Hannon", "gender": "F", "birtdate": "31 October 1865", "birtplac": "Acton, Middlesex, Massachusetts, United States", "deatdate": "8 August 1964", "deatplac": "Dorchester, Suffolk, Massachusetts, United States", "chrdate": null, "chrplac": null, "buridate": "1964", "buriplac": "West Roxbury, Suffolk, Massachusetts, United States of America", "parents": ["MVFK-TQP", "MVFK-TWD"], "children": [["LV7R-QM8", "L83V-TTZ", "L89N-K6V"], ["LV7R-QM8", "L83V-TTZ", "LHTZ-LKY"], ["LV7R-QM8", "L83V-TTZ", "KG83-BL5"], ["LV7R-QM8", "L83V-TTZ", "LWRR-VRV"], ["LV7R-QM8", "L83V-TTZ", "LTC6-2SD"], ["LV7R-QM8", "L83V-TTZ", "MK43-JTP"], ["LV7R-QM8", "L83V-TTZ", "LDXR-7MW"], ["LV7R-QM8", "L83V-TTZ", "9JZ6-8Z3"], ["LV7R-QM8", "L83V-TTZ", "9JG2-46T"], ["LV7R-QM8", "L83V-TTZ", "LTQX-6CK"], ["LV7R-QM8", "L83V-TTZ", "LWLT-LFR"], ["LV7R-QM8", "L83V-TTZ", "LTC6-KVZ"], ["LV7R-QM8", "L83V-TTZ", "LTC6-V7K"], ["LV7R-QM8", "L83V-TTZ", "M32B-9WM"], ["LV7R-QM8", "L83V-TTZ", "MD9D-QV4"]], "spouses": [["LV7R-QM8", "L83V-TTZ", "MNQ8-Q9L"]]}
{"num": 8, "fid": "LCVQ-NGT", "famc_fid": [["LRG3-FJ2", "LRG3-F98"]], "fams_fid": [["LCVQ-NGT", "L83V-TTH"]], "famc_num": [10], "fams_num": [4], "given": "Patrick", "surname": "Kennedy", "gender": "M", "birtdate": "16 February 1823", "birtplac": "Dunganstown, (Whitechurch, New Ross, County Wexford) Ireland", "deatdate": "22 November 1858", "deatplac": "Boston, Massachusetts, USA", "chrdate": null, "chrplac": null, "buridate": "23 Nov 1858", "buriplac": "Cambridge, Middlesex Co, MA", "parents": ["LRG3-FJ2", "LRG3-F98"], "children": [["LCVQ-NGT", "L83V-TTH", "L6YW-X59"], ["LCVQ-NGT", "L83V-TTH", "MT5X-Q7Z"], ["LCVQ-NGT", "L83V-TTH", "MT5X-Q72"], ["LCVQ-NGT", "L83V-TTH", "KZ2X-SKM"], ["LCVQ-NGT", "L83V-TTH", "KGK2-SFX"], ["LCVQ-NGT", "L83V-TTH", "MT5X-Q4Q"], ["LCVQ-NGT", "L83V-TTH", "LRG3-41R"], ["LCVQ-NGT", "L83V-TTH", "LHX8-4DQ"], ["LCVQ-NGT", "L83V-TTH", "LH6W-6YM"], ["LCVQ-NGT", "L83V-TTH", "MT5X-Q4V"], ["LCVQ-NGT", "L83V-TTH", "L89N-K62"], ["LCVQ-NGT", "L83V-TTH", "MT5X-QH3"], ["LCVQ-NGT", "L83V-TTH", "LC2H-7NZ"]], "spouses": [["LCVQ-NGT", "L83V-TTH", "MN9W-JXL"]]}
{"num": 9, "fid": "L83V-TTH", "famc_fid": [["9KDW-R74", "L6YW-F5M"]], "fams_fid": [["LCVQ-NGT", "L83V-TTH"]], "famc_num": [9], "fams_num": [4], "given": "Bridget", "surname": "Murphy", "gender": "F", "birtdate": "1821", "birtplac": "Dunganstown, Wexford, Ireland", "deatdate": "20 December 1888", "deatplac": "Boston, Suffolk, Massachusetts, United States", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": "Malden, Middlesex Co, MA", "parents": ["9KDW-R74", "L6YW-F5M"], "children": [["LCVQ-NGT", "L83V-TTH", "L6YW-X59"], ["LCVQ-NGT", "L83V-TTH", "MT5X-Q7Z"], ["LCVQ-NGT", "L83V-TTH", "MT5X-Q72"], ["LCVQ-NGT", "L83V-TTH", "KZ2X-SKM"], ["LCVQ-NGT", "L83V-TTH", "KGK2-SFX"], ["LCVQ-NGT", "L83V-TTH", "MT5X-Q4Q"], ["LCVQ-NGT", "L83V-TTH", "LRG3-41R"], ["LCVQ-NGT", "L83V-TTH", "LHX8-4DQ"], ["LCVQ-NGT", "L83V-TTH", "LH6W-6YM"], ["LCVQ-NGT", "L83V-TTH", "MT5X-Q4V"], ["LCVQ-NGT", "L83V-TTH", "L89N-K62"], ["LCVQ-NGT", "L83V-TTH", "MT5X-QH3"], ["LCVQ-NGT", "L83V-TTH", "LC2H-7NZ"]], "spouses": [["LCVQ-NGT", "L83V-TTH", "MN9W-JXL"]]}
{"num": 10, "fid": "KCRN-GRR", "famc_fid": [], "fams_fid": [["KCRN-GRR", "K8G9-3WV"], ["KCRN-GRR", "LTVL-K2F"]], "famc_num": [], "fams_num": [5, 15], "given": "Thomas Wilmouth", "surname": "Fitzgerald", "gender": "M", "birtdate": "4 December 1823", "birtplac": "Bruff, County Limerick, Ireland", "deatdate": "May 19 1885", "deatplac": "Boston, Suffolk, Massachusetts, United States", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": [null, null], "children": [["KCRN-GRR", "LTVL-K2F", "KP7V-FMM"], ["KCRN-GRR", "K8G9-3WV", "KP7V-FMM"], ["KCRN-GRR", "LTVL-K2F", "LV7R-QM8"]], "spouses": [["KCRN-GRR", "K8G9-3WV", "MKGW-NWB"], ["KCRN-GRR", "LTVL-K2F", "MH9Y-B1B"]]}
{"num": 11, "fid": "LTVL-K2F", "famc_fid": [], "fams_fid": [["KCRN-GRR", "LTVL-K2F"]], "famc_num": [], "fams_num": [5], "given": "Rosanna", "surname": "Cox", "gender": "F", "birtdate": "12/4/1823", "birtplac": null, "deatdate": "05/1885", "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": [null, null], "children": [["KCRN-GRR", "LTVL-K2F", "KP7V-FMM"], ["KCRN-GRR", "LTVL-K2F", "LV7R-QM8"]], "spouses": [["KCRN-GRR", "LTVL-K2F", "MH9Y-B1B"]]}
{"num": 12, "fid": "MVFK-TQP", "famc_fid": [["KPQB-BJP", "KHJW-61X"]], "fams_fid": [["MVFK-TQP", "KGW2-2P4"], ["MVFK-TQP", "MVFK-TWD"]], "famc_num": [13], "fams_num": [50, 6], "given": "Michael", "surname": "Hannon", "gender": "M", "birtdate": "29 September 1832", "birtplac": "Loughgur, County Limerick, Ireland", "deatdate": "19 May 1885", "deatplac": "Boston, Suffolk, Massachusetts, United States", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": ["KPQB-BJP", "KHJW-61X"], "children": [["MVFK-TQP", "MVFK-TWD", "LKL8-VJ9"], ["MVFK-TQP", "MVFK-TWD", "LVDF-8XR"], ["MVFK-TQP", "MVFK-TWD", "K4V4-MQR"], ["MVFK-TQP", "MVFK-TWD", "LVDF-8N5"], ["MVFK-TQP", "MVFK-TWD", "MJSF-TX1"], ["MVFK-TQP", "MVFK-TWD", "L83V-TTZ"], ["MVFK-TQP", "MVFK-TWD", "MJS6-8MQ"], ["MVFK-TQP", "MVFK-TWD", "KGW2-2P9"], ["MVFK-TQP", "MVFK-TWD", "LB3F-SQG"], ["MVFK-TQP", "MVFK-TWD", "MJSX-84F"]], "spouses": [["MVFK-TQP", "MVFK-TWD", "MKVB-PZC"], ["MVFK-TQP", "KGW2-2P4", "M29D-M72"]]}
{"num": 13, "fid": "MVFK-TWD", "famc_fid": [["KPQB-B7X", "KPQB-BZT"]], "fams_fid": [["MVFK-TQP", "MVFK-TWD"]], "famc_num": [12], "fams_num": [6], "given": "Mary Anne", "surname": "Fitzgerald", "gender": "F", "birtdate": "27 May 1834", "birtplac": "Bruff, Limerick, Ireland", "deatdate": "1 JUL 1904", "deatplac": "Concord, Middlesex, Massachusetts, United States", "chrdate": "9 May 1832", "chrplac": "Bruff, County Limerick, Ireland", "buridate": "03 Jul 1904", "buriplac": null, "parents": ["KPQB-B7X", "KPQB-BZT"], "children": [["MVFK-TQP", "MVFK-TWD", "LKL8-VJ9"], ["MVFK-TQP", "MVFK-TWD", "LVDF-8XR"], ["MVFK-TQP", "MVFK-TWD", "K4V4-MQR"], ["MVFK-TQP", "MVFK-TWD", "LVDF-8N5"], ["MVFK-TQP", "MVFK-TWD", "MJSF-TX1"], ["MVFK-TQP", "MVFK-TWD", "L83V-TTZ"], ["MVFK-TQP", "MVFK-TWD", "MJS6-8MQ"], ["MVFK-TQP", "MVFK-TWD", "KGW2-2P9"], ["MVFK-TQP", "MVFK-TWD", "LB3F-SQG"], ["MVFK-TQP", "MVFK-TWD", "MJSX-84F"]], "spouses": [["MVFK-TQP", "MVFK-TWD", "MKVB-PZC"]]}
{"num": 14, "fid": "LZ38-WH7", "famc_fid": [["L7J2-S8N", "L7J2-S6Z"]], "fams_fid": [["LZ38-WH7", "LZ38-WHX"]], "famc_num": [8], "fams_num": [7], "given": "James", "surname": "Hickey", "gender": "M", "birtdate": "1836", "birtplac": ", KIlkenney, Ireland, Ireland", "deatdate": "1900", "deatplac": "Boston, Massachusets, USA", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": ["L7J2-S8N", "L7J2-S6Z"], "children": [["LZ38-WH7", "LZ38-WHX", "L89N-K6L"], ["LZ38-WH7", "LZ38-WHX", "9KDW-59P"], ["LZ38-WH7", "LZ38-WHX", "9KDW-59B"], ["LZ38-WH7", "LZ38-WHX", "9KDW-5S3"], ["LZ38-WH7", "LZ38-WHX", "L7W4-PTV"]], "spouses": [["LZ38-WH7", "LZ38-WHX", "MZLL-W4C"]]}
{"num": 15, "fid": "LZ38-WHX", "famc_fid": [["KPQB-T8S", "KPQB-THZ"]], "fams_fid": [["LZ38-WH7", "LZ38-WHX"]], "famc_num": [11], "fams_num": [7], "given": "Margaret Martha", "surname": "Field", "gender": "F", "birtdate": "1813", "birtplac": ", KIlkenney, Ireland, Ireland", "deatdate": "1911", "deatplac": "Boston, Massachusetts, USA", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": ["KPQB-T8S", "KPQB-THZ"], "children": [["LZ38-WH7", "LZ38-WHX", "L89N-K6L"], ["LZ38-WH7", "LZ38-WHX", "9KDW-59P"], ["LZ38-WH7", "LZ38-WHX", "9KDW-59B"], ["LZ38-WH7", "LZ38-WHX", "9KDW-5S3"], ["LZ38-WH7", "LZ38-WHX", "L7W4-PTV"]], "spouses": [["LZ38-WH7", "LZ38-WHX", "MZLL-W4C"]]}
{"num": 16, "fid": "L7J2-S8N", "famc_fid": [], "fams_fid": [["L7J2-S8N", "L7J2-S6Z"]], "famc_num": [], "fams_num": [8], "given": "Michael", "surname": "Hickey", "gender": "M", "birtdate": "Abt 1790", "birtplac": ",, Ireland", "deatdate": "       1870", "deatplac": "Boston, Suffolk, Mass, USA", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": [["L7J2-S8N", "L7J2-S6Z", "MWHS-RYH"], ["L7J2-S8N", "L7J2-S6Z", "MWHS-RYV"], ["L7J2-S8N", "L7J2-S6Z", "MWHS-RYR"], ["L7J2-S8N", "L7J2-S6Z", "MWHS-RB9"], ["L7J2-S8N", "L7J2-S6Z", "LZ38-WH7"], ["L7J2-S8N", "L7J2-S6Z", "MWHS-RB7"]], "spouses": [["L7J2-S8N", "L7J2-S6Z", "MC2X-SPB"]]}
{"num": 17, "fid": "L7J2-S6Z", "famc_fid": [], "fams_fid": [["L7J2-S8N", "L7J2-S6Z"]], "famc_num": [], "fams_num": [8], "given": "Catherine", "surname": "Hasset", "gender": "F", "birtdate": "Abt 1800", "birtplac": ",, Ireland", "deatdate": "UNKNOWN", "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": [["L7J2-S8N", "L7J2-S6Z", "MWHS-RYH"], ["L7J2-S8N", "L7J2-S6Z", "MWHS-RYV"], ["L7J2-S8N", "L7J2-S6Z", "MWHS-RYR"], ["L7J2-S8N", "L7J2-S6Z", "MWHS-RB9"], ["L7J2-S8N", "L7J2-S6Z", "LZ38-WH7"], ["L7J2-S8N", "L7J2-S6Z", "MWHS-RB7"]], "spouses": [["L7J2-S8N", "L7J2-S6Z", "MC2X-SPB"]]}
{"num": 18, "fid": "9KDW-R74", "famc_fid": [], "fams_fid": [["9KDW-R74", "L6YW-F5M"]], "famc_num": [], "fams_num": [9], "given": "Richard", "surname": "Murphy", "gender": "M", "birtdate": "ABT 1795", "birtplac": "Wexford, Ireland", "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": [["9KDW-R74", "L6YW-F5M", "L83V-TTH"], ["9KDW-R74", "L6YW-F5M", "L23M-LYV"]], "spouses": [["9KDW-R74", "L6YW-F5M", "MNC2-FJ8"]]}
{"num": 19, "fid": "L6YW-F5M", "famc_fid": [], "fams_fid": [["9KDW-R74", "L6YW-F5M"]], "famc_num": [], "fams_num": [9], "given": "Mary", "surname": "Barron", "gender": "F", "birtdate": "1800", "birtplac": "Wexford County, Ireland", "deatdate": "1860", "deatplac": "Ireland", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": [["9KDW-R74", "L6YW-F5M", "L83V-TTH"], ["9KDW-R74", "L6YW-F5M", "L23M-LYV"]], "spouses": [["9KDW-R74", "L6YW-F5M", "MNC2-FJ8"]]}
{"num": 20, "fid": "LRG3-FJ2", "famc_fid": [], "fams_fid": [["LRG3-FJ2", "LRG3-F98"]], "famc_num": [], "fams_num": [10], "given": "James", "surname": "Kennedy", "gender": "M", "birtdate": "1770", "birtplac": "Ireland", "deatdate": "1840", "deatplac": "Ireland", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": [["LRG3-FJ2", "LRG3-F98", "L78G-MWH"], ["LRG3-FJ2", "LRG3-F98", "KPW9-YJY"], ["LRG3-FJ2", "LRG3-F98", "LRG3-2BN"], ["LRG3-FJ2", "LRG3-F98", "LCVQ-NGT"], ["LRG3-FJ2", "LRG3-F98", "LYC7-WSH"]], "spouses": [["LRG3-FJ2", "LRG3-F98", "MV6Y-HZ4"]]}
{"num": 21, "fid": "LRG3-F98", "famc_fid": [], "fams_fid": [["LRG3-FJ2", "LRG3-F98"]], "famc_num": [], "fams_num": [10], "given": "Maria", "surname": "Maiden", "gender": "F", "birtdate": "1779", "birtplac": null, "deatdate": "16 February 1835", "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": [["LRG3-FJ2", "LRG3-F98", "L78G-MWH"], ["LRG3-FJ2", "LRG3-F98", "KPW9-YJY"], ["LRG3-FJ2", "LRG3-F98", "LRG3-2BN"], ["LRG3-FJ2", "LRG3-F98", "LCVQ-NGT"], ["LRG3-FJ2", "LRG3-F98", "LYC7-WSH"]], "spouses": [["LRG3-FJ2", "LRG3-F98", "MV6Y-HZ4"]]}
{"num": 22, "fid": "KPQB-T8S", "famc_fid": [], "fams_fid": [["KPQB-T8S", "KPQB-THZ"]], "famc_num": [], "fams_num": [11], "given": "Patrick", "surname": "Field", "gender": "M", "birtdate": "1786", "birtplac": "Kilkenny, Ireland, United Kingdom", "deatdate": "UNKNOWN", "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": [["KPQB-T8S", "KPQB-THZ", "LZ38-WHX"]], "spouses": [["KPQB-T8S", "KPQB-THZ", "MHMK-LJM"]]}
{"num": 23, "fid": "KPQB-THZ", "famc_fid": [], "fams_fid": [["KPQB-T8S", "KPQB-THZ"]], "famc_num": [], "fams_num": [11], "given": "Mary", "surname": "Sheehy", "gender": "F", "birtdate": "1788", "birtplac": ", KIlkenney, Ireland, Ireland", "deatdate": "UNKNOWN", "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": [["KPQB-T8S", "KPQB-THZ", "LZ38-WHX"]], "spouses": [["KPQB-T8S", "KPQB-THZ", "MHMK-LJM"]]}
{"num": 24, "fid": "KPQB-B7X", "famc_fid": [], "fams_fid": [["KPQB-B7X", null], ["KPQB-B7X", "KPQB-BZT"]], "famc_num": [], "fams_num": [16, 12], "given": "Edmund Andrew", "surname": "FitzGerald", "gender": "M", "birtdate": "21 Aug 1798", "birtplac": "Lough, Limerick, Ireland", "deatdate": "27 December 1883", "deatplac": "Boston, Suffolk, Massachusetts, United States", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": [["KPQB-B7X", "KPQB-BZT", "LR37-WJJ"], ["KPQB-B7X", "KPQB-BZT", "LR37-61R"], ["KPQB-B7X", "KPQB-BZT", "LY17-M27"], ["KPQB-B7X", "KPQB-BZT", "LY1Q-N97"], ["KPQB-B7X", "KPQB-BZT", "MVFK-TWD"], ["KPQB-B7X", null, "LBKC-HY5"]], "spouses": [["KPQB-B7X", "KPQB-BZT", "MCPY-YZ3"]]}
{"num": 25, "fid": "KPQB-BZT", "famc_fid": [], "fams_fid": [["KPQB-B7X", "KPQB-BZT"]], "famc_num": [], "fams_num": [12], "given": "Mary Caitlin", "surname": "Linnehan", "gender": "F", "birtdate": "ABT. 1791", "birtplac": null, "deatdate": "bet 9 May 1832 & 3 Mar 1835", "deatplac": "prob. Bruff or Knockaney, Limerick, Ireland", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": [["KPQB-B7X", "KPQB-BZT", "LR37-WJJ"], ["KPQB-B7X", "KPQB-BZT", "LR37-61R"], ["KPQB-B7X", "KPQB-BZT", "LY17-M27"], ["KPQB-B7X", "KPQB-BZT", "LY1Q-N97"], ["KPQB-B7X", "KPQB-BZT", "MVFK-TWD"]], "spouses": [["KPQB-B7X", "KPQB-BZT", "MCPY-YZ3"]]}
{"num": 26, "fid": "KPQB-BJP", "famc_fid": [], "fams_fid": [["KPQB-BJP", "KHJW-61X"]], "famc_num": [], "fams_num": [13], "given": "John", "surname": "Hannon", "gender": "M", "birtdate": "       1789", "birtplac": "Ireland", "deatdate": "1835", "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": [["KPQB-BJP", "KHJW-61X", "MVFK-TQP"]], "spouses": [["KPQB-BJP", "KHJW-61X", "MH9B-M14"]]}
{"num": 27, "fid": "KHJW-61X", "famc_fid": [], "fams_fid": [["KPQB-BJP", "KHJW-61X"]], "famc_num": [], "fams_num": [13], "given": "Eellen", "surname": "Noonan", "gender": "F", "birtdate": "ABT 1793", "birtplac": "Ireland", "deatdate": "       1877", "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": [["KPQB-BJP", "KHJW-61X", "MVFK-TQP"]], "spouses": [["KPQB-BJP", "KHJW-61X", "MH9B-M14"]]}
{"num": 28, "fid": "LRF8-RKC", "famc_fid": [["L89N-K6J", "L89N-K6V"]], "fams_fid": [], "famc_num": [1], "fams_num": [], "given": "Joseph Patrick \"Joe\"", "surname": "Kennedy", "gender": "M", "birtdate": "25 July 1915", "birtplac": "Hull, Plymouth, Massachusetts, United States", "deatdate": "12 August 1944", "deatplac": "Suffolk, England, United Kingdom", "chrdate": null, "chrplac": null, "buridate": "1944", "buriplac": "Coton, South Cambridgeshire District, Cambridgeshire, England", "parents": null, "children": null, "spouses": null}
{"num": 29, "fid": "LBKC-ZV5", "famc_fid": [[null, "L89N-K6V"]], "fams_fid": [], "famc_num": [14], "fams_num": [], "given": "John \"Jack\"Fitzgerald", "surname": "Kennedy", "gender": "M", "birtdate": "1917", "birtplac": null, "deatdate": "1963", "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 30, "fid": "LZNR-GPG", "famc_fid": [["L89N-K6J", "L89N-K6V"]], "fams_fid": [], "famc_num": [1], "fams_num": [], "given": "Rose Marie \"Rosemary\"", "surname": "Kennedy", "gender": "F", "birtdate": "13 September 1918", "birtplac": "Brookline, Suffolk, Massachusetts, United States", "deatdate": "7 January 2005", "deatplac": "Jefferson, Jefferson, Wisconsin, United States", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": "Holyhood Cemetery, Brookline, Norfolk, Massachusetts, United States", "parents": null, "children": null, "spouses": null}
{"num": 31, "fid": "LZNR-GGF", "famc_fid": [["L89N-K6J", "L89N-K6V"]], "fams_fid": [["L83V-TTD", "LZNR-GGF"]], "famc_num": [1], "fams_num": [38], "given": "Kathleen Agnes \"Kick\"", "surname": "Kennedy", "gender": "F", "birtdate": "20 February 1920", "birtplac": "Brookline, Norfolk, Massachusetts, United States", "deatdate": "13 MAY 1948", "deatplac": "Chatsworth, Derbyshire, England, United Kingdom", "chrdate": null, "chrplac": null, "buridate": "May 1944", "buriplac": "Chatsworth, Derbyshire, England, United Kingdom", "parents": null, "children": null, "spouses": [["L83V-TTD", "LZNR-GGF", "MJLB-MSQ"]]}
{"num": 32, "fid": "LJL3-M17", "famc_fid": [["L89N-K6J", "L89N-K6V"]], "fams_fid": [["LRFD-48Z", "LJL3-M17"]], "famc_num": [1], "fams_num": [41], "given": "Eunice Mary", "surname": "Kennedy", "gender": "F", "birtdate": "10 July 1921", "birtplac": "Brookline, Massachusetts, United States", "deatdate": "11 August 2009", "deatplac": "Hyannis Port, Barnstable, Massachusetts, United States", "chrdate": null, "chrplac": null, "buridate": "2009", "buriplac": "Centerville, Barnstable, Massachusetts, United States of America", "parents": null, "children": null, "spouses": [["LRFD-48Z", "LJL3-M17", "M2MF-YWN"]]}
{"num": 33, "fid": "LRF8-G8C", "famc_fid": [["L89N-K6J", "L89N-K6V"]], "fams_fid": [["L89N-KXS", "LRF8-G8C"]], "famc_num": [1], "fams_num": [40], "given": "Patricia Helen \"Pat\"", "surname": "Kennedy", "gender": "F", "birtdate": "6 May 1924", "birtplac": "Brookline, Norfolk, Massachusetts, United States", "deatdate": "17 September 2006", "deatplac": "Manhattan, New York City, New York, United States", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": "Southampton Cemetery, Southampton, Suffolk, New York, United States", "parents": null, "children": null, "spouses": [["L89N-KXS", "LRF8-G8C", "MVDB-NVR"]]}
{"num": 34, "fid": "LZNR-GRZ", "famc_fid": [["L89N-K6J", "L89N-K6V"]], "fams_fid": [["LZNR-GRZ", "KP7W-L4X"]], "famc_num": [1], "fams_num": [35], "given": "Robert Francis", "surname": "Kennedy", "gender": "M", "birtdate": "20 November 1925", "birtplac": "Brookline, Brookline, Norfolk, Massachusetts, United States", "deatdate": "6 June 1968", "deatplac": "Good Samaritan Hospital Los Angeles, Los Angeles, California, United States", "chrdate": null, "chrplac": null, "buridate": "1968", "buriplac": "Arlington National Cemetery, Arlington, Virginia, United States", "parents": null, "children": null, "spouses": [["LZNR-GRZ", "KP7W-L4X", "MCPH-NN2"]]}
{"num": 35, "fid": "LZNR-GY3", "famc_fid": [["L89N-K6J", "L89N-K6V"]], "fams_fid": [["LZNR-GY3", "LVJ5-43Y"], ["LZNR-GY3", "LLHG-514"]], "famc_num": [1], "fams_num": [58, 59], "given": "Edward Moore \"Ted\"", "surname": "Kennedy", "gender": "M", "birtdate": "22 February 1932", "birtplac": "Brookline, Norfolk, Massachusetts, United States", "deatdate": "August 25, 2009", "deatplac": "Hyannis Port, Barnstable, Massachusetts, United States", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": "Arlington, Arlington, Virginia, United States", "parents": null, "children": null, "spouses": [["LZNR-GY3", "LVJ5-43Y", "MN4X-HRF"], ["LZNR-GY3", "LLHG-514", "MJ64-Y6N"]]}
{"num": 36, "fid": "LR37-WJJ", "famc_fid": [["KPQB-B7X", "KPQB-BZT"]], "fams_fid": [], "famc_num": [12], "fams_num": [], "given": "Bridget Caitlin", "surname": "Fitzgerald", "gender": "F", "birtdate": "22 June 1829", "birtplac": "Bruff, County Limerick, Ireland", "deatdate": "April 1926", "deatplac": null, "chrdate": "29 September 1830", "chrplac": "Bruff, County Limerick, Ireland", "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 37, "fid": "LR37-61R", "famc_fid": [["KPQB-B7X", "KPQB-BZT"]], "fams_fid": [], "famc_num": [12], "fams_num": [], "given": "Hanora", "surname": "Fitzgerald", "gender": "F", "birtdate": "1829", "birtplac": "County Limerick, Ireland", "deatdate": null, "deatplac": null, "chrdate": "22 June 1829", "chrplac": "Bruff, County Limerick, Ireland", "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 38, "fid": "LY17-M27", "famc_fid": [["KPQB-B7X", "KPQB-BZT"]], "fams_fid": [], "famc_num": [12], "fams_num": [], "given": "Johanna", "surname": "Fitzgerald", "gender": "F", "birtdate": null, "birtplac": null, "deatdate": null, "deatplac": null, "chrdate": "29 September 1830", "chrplac": "Bruff, County Limerick, Ireland", "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 39, "fid": "LY1Q-N97", "famc_fid": [["KPQB-B7X", "KPQB-BZT"]], "fams_fid": [], "famc_num": [12], "fams_num": [], "given": "Mary", "surname": "Fitzgerald", "gender": "F", "birtdate": null, "birtplac": null, "deatdate": null, "deatplac": null, "chrdate": "9 May 1832", "chrplac": "Bruff, County Limerick, Ireland", "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 40, "fid": "K8Z9-VJ6", "famc_fid": [["L89N-K62", "L89N-K6L"]], "fams_fid": [], "famc_num": [2], "fams_num": [], "given": "Frances Benedict", "surname": "Kennedy", "gender": "M", "birtdate": "March 1891", "birtplac": "Boston, Suffolk, Massachusetts, United States", "deatdate": "15 June 1892", "deatplac": null, "chrdate": "22 March 1891", "chrplac": "East Boston, Boston, Suffolk, Massachusetts, United States", "buridate": null, "buriplac": "Malden, Middlesex, Massachusetts, United States", "parents": null, "children": null, "spouses": null}
{"num": 41, "fid": "K6MQ-7TK", "famc_fid": [["L89N-K62", "L89N-K6L"]], "fams_fid": [["K6MY-9V3", "K6MQ-7TK"]], "famc_num": [2], "fams_num": [62], "given": "Mary Loretta", "surname": "Kennedy", "gender": "F", "birtdate": "6 August 1892", "birtplac": "Boston,Suffolk,Massachusetts", "deatdate": "18 November 1972", "deatplac": "Winfield, DuPage, Illinois, United States", "chrdate": "18 AUG 1892", "chrplac": "East Boston, Suffolk Co, Ma", "buridate": "1972", "buriplac": "Saint Augustine, St. Johns, Florida, United States of America", "parents": null, "children": null, "spouses": [["K6MY-9V3", "K6MQ-7TK", "M4VV-TSC"]]}
{"num": 42, "fid": "K6S9-BCF", "famc_fid": [["L89N-K62", "L89N-K6L"]], "fams_fid": [["LHDK-RKJ", "K6S9-BCF"], ["LYPF-3BS", "K6S9-BCF"]], "famc_num": [2], "fams_num": [20, 21], "given": "Margaret Louise", "surname": "Kennedy", "gender": "F", "birtdate": "22 OCT 1898", "birtplac": "East Boston, Suffolk, Massachusetts, United States", "deatdate": "14 NOV 1974", "deatplac": "Brookline, Norfolk, Massachusetts, United States", "chrdate": "30 OCT 1898", "chrplac": "East Boston, Suffolk Co, Ma", "buridate": null, "buriplac": "Malden, Middlesex Co, Ma", "parents": null, "children": null, "spouses": [["LHDK-RKJ", "K6S9-BCF", "M4VV-1RW"], ["LYPF-3BS", "K6S9-BCF", "MKN7-RD6"]]}
{"num": 43, "fid": "MWHS-RYH", "famc_fid": [["L7J2-S8N", "L7J2-S6Z"]], "fams_fid": [], "famc_num": [8], "fams_num": [], "given": "Patrick", "surname": "Hickey", "gender": "M", "birtdate": "1 Aug 1819", "birtplac": ", Clare, Ireland", "deatdate": "20 Jun 1894", "deatplac": "Brookline, Norfolk, MA", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 44, "fid": "MWHS-RYV", "famc_fid": [["L7J2-S8N", "L7J2-S6Z"]], "fams_fid": [], "famc_num": [8], "fams_num": [], "given": "Michael", "surname": "Hickey", "gender": "M", "birtdate": "6 Jan 1823", "birtplac": ", Clare, Ireland", "deatdate": "14 Apr 1893", "deatplac": "Brookline, Norfolk, MA", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 45, "fid": "MWHS-RYR", "famc_fid": [["L7J2-S8N", "L7J2-S6Z"]], "fams_fid": [], "famc_num": [8], "fams_num": [], "given": "Thomas", "surname": "Hickey", "gender": "M", "birtdate": null, "birtplac": null, "deatdate": null, "deatplac": null, "chrdate": "2 Sep 1830", "chrplac": "Killaloe, Bunratty, Clare, Ireland", "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 46, "fid": "MWHS-RB9", "famc_fid": [["L7J2-S8N", "L7J2-S6Z"]], "fams_fid": [], "famc_num": [8], "fams_num": [], "given": "John", "surname": "Hickey", "gender": "M", "birtdate": null, "birtplac": null, "deatdate": null, "deatplac": null, "chrdate": "3 Feb 1832", "chrplac": "Killaloe, Bunratty, Clare, Ireland", "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 47, "fid": "MWHS-RB7", "famc_fid": [["L7J2-S8N", "L7J2-S6Z"]], "fams_fid": [], "famc_num": [8], "fams_num": [], "given": "Charles", "surname": "Hickey", "gender": "M", "birtdate": null, "birtplac": null, "deatdate": null, "deatplac": null, "chrdate": "18 Aug 1839", "chrplac": "Killaloe, Bunratty, Clare, Ireland", "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 48, "fid": "L23M-LYV", "famc_fid": [["9KDW-R74", "L6YW-F5M"]], "fams_fid": [["L23M-G3Q", "L23M-LYV"]], "famc_num": [9], "fams_num": [55], "given": "Ann", "surname": "Murphy", "gender": "F", "birtdate": "1834", "birtplac": "Ireland", "deatdate": "17 July 1893", "deatplac": "Salem, Essex, Massachusetts, United States", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": "Salem, Essex, Massachusetts, United States", "parents": null, "children": null, "spouses": [["L23M-G3Q", "L23M-LYV", "MNT7-LBW"]]}
{"num": 49, "fid": "KP7V-FMM", "famc_fid": [["KCRN-GRR", "K8G9-3WV"], ["KCRN-GRR", "LTVL-K2F"]], "fams_fid": [["LJ19-331", "KP7V-FMM"], ["KLLY-TXP", "KP7V-FMM"]], "famc_num": [5, 15], "fams_num": [52, 53], "given": "Ellen", "surname": "Wilmouth", "gender": "F", "birtdate": "1797", "birtplac": "Bruff, 5310, Ireland", "deatdate": "17 Nov 1875", "deatplac": "Boston, Suffolk , MA", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": [["LJ19-331", "KP7V-FMM", "MFBH-F3Q"], ["KLLY-TXP", "KP7V-FMM", "M29Q-XRC"]]}
{"num": 50, "fid": "K8G9-3WV", "famc_fid": [], "fams_fid": [["KCRN-GRR", "K8G9-3WV"]], "famc_num": [], "fams_num": [15], "given": "Bridget", "surname": "Unknown", "gender": "F", "birtdate": "ABT 1770", "birtplac": "Boston, Suffolk, Mass, USA", "deatdate": "ABT. 1866", "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": [["KCRN-GRR", "K8G9-3WV", "MKGW-NWB"]]}
{"num": 51, "fid": "L6YW-X59", "famc_fid": [["LCVQ-NGT", "L83V-TTH"]], "fams_fid": [["L6YW-FK4", "L6YW-X59"]], "famc_num": [4], "fams_num": [60], "given": "Margaret", "surname": "Murphy", "gender": "F", "birtdate": "1841", "birtplac": "Of Canada West", "deatdate": "1929", "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": [["L6YW-FK4", "L6YW-X59", "MX6J-Q32"]]}
{"num": 52, "fid": "MT5X-Q7Z", "famc_fid": [["LCVQ-NGT", "L83V-TTH"]], "fams_fid": [], "famc_num": [4], "fams_num": [], "given": "Andrew", "surname": "Kennedy", "gender": "M", "birtdate": "1847", "birtplac": "Canada West", "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 53, "fid": "MT5X-Q72", "famc_fid": [["LCVQ-NGT", "L83V-TTH"]], "fams_fid": [["LK33-F5K", "MT5X-Q72"]], "famc_num": [4], "fams_num": [33], "given": "Mary Ann", "surname": "Kennedy", "gender": "F", "birtdate": "       1850", "birtplac": "Canada West", "deatdate": "09 Nov 1890", "deatplac": "Pittsfield, Massachusetts", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": [["LK33-F5K", "MT5X-Q72", "MKGR-R45"]]}
{"num": 54, "fid": "KZ2X-SKM", "famc_fid": [["LCVQ-NGT", "L83V-TTH"]], "fams_fid": [["K6WT-NWT", "KZ2X-SKM"]], "famc_num": [4], "fams_num": [51], "given": "Mary", "surname": "Kennedy", "gender": "F", "birtdate": "09 AUG 1851", "birtplac": "Boston,Suffolk,Massachusetts", "deatdate": "7 MAR 1926", "deatplac": "Boston, Suffolk Co, MA", "chrdate": "10 AUG 1851", "chrplac": "East Boston,Suffolk Co,MA", "buridate": "MAR 1926", "buriplac": "Malden,Middlesex Co,MA", "parents": null, "children": null, "spouses": [["K6WT-NWT", "KZ2X-SKM", "M3BY-KRV"]]}
{"num": 55, "fid": "KGK2-SFX", "famc_fid": [["LCVQ-NGT", "L83V-TTH"]], "fams_fid": [["K8YS-D2Y", "KGK2-SFX"]], "famc_num": [4], "fams_num": [39], "given": "Joanna L.", "surname": "Kennedy", "gender": "F", "birtdate": "27 Nov 1852", "birtplac": "Boston, Middlesex, Massachusetts, USA", "deatdate": "23 FEB 1926", "deatplac": "Revere, Suffolk Co, MA", "chrdate": "4 DEC 1852", "chrplac": "East Boston,Suffolk Co,MA", "buridate": "FEB 1926", "buriplac": "Malden,Middlesex Co,MA", "parents": null, "children": null, "spouses": [["K8YS-D2Y", "KGK2-SFX", "MJL6-GY6"]]}
{"num": 56, "fid": "MT5X-Q4Q", "famc_fid": [["LCVQ-NGT", "L83V-TTH"]], "fams_fid": [], "famc_num": [4], "fams_num": [], "given": "Mich", "surname": "Kennedy", "gender": "M", "birtdate": "       1853", "birtplac": "Canada West", "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 57, "fid": "LRG3-41R", "famc_fid": [["LCVQ-NGT", "L83V-TTH"]], "fams_fid": [], "famc_num": [4], "fams_num": [], "given": "John", "surname": "Kennedy", "gender": "M", "birtdate": "4 January 1854", "birtplac": "Of Ontario, Canada", "deatdate": "24 September 1855", "deatplac": "Of Ontario, Canada", "chrdate": null, "chrplac": null, "buridate": "1855", "buriplac": "Cambridge, Middlesex, Massachusetts, United States of America", "parents": null, "children": null, "spouses": null}
{"num": 58, "fid": "LHX8-4DQ", "famc_fid": [["LCVQ-NGT", "L83V-TTH"]], "fams_fid": [["LHX8-48T", "LHX8-4DQ"]], "famc_num": [4], "fams_num": [30], "given": "Ann", "surname": "Gallagher", "gender": "F", "birtdate": "       1855", "birtplac": "New York", "deatdate": "01 Oct 1878", "deatplac": "New Bedford, Bristol, Massachusetts", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": [["LHX8-48T", "LHX8-4DQ", "MMX8-X4H"]]}
{"num": 59, "fid": "LH6W-6YM", "famc_fid": [["LCVQ-NGT", "L83V-TTH"]], "fams_fid": [["LW4X-TYN", "LH6W-6YM"]], "famc_num": [4], "fams_num": [34], "given": "Margaret M.", "surname": "Kennedy", "gender": "F", "birtdate": "18 July 1855", "birtplac": "Boston, Suffolk, Massachusetts, United States", "deatdate": "2 APR 1929", "deatplac": "Revere, Suffolk Co, MA", "chrdate": "22 JUL 1855", "chrplac": "East Boston, Suffolk Co, Ma", "buridate": null, "buriplac": "Malden, Middlesex Co, MA", "parents": null, "children": null, "spouses": [["LW4X-TYN", "LH6W-6YM", "M8JL-HC3"]]}
{"num": 60, "fid": "MT5X-Q4V", "famc_fid": [["LCVQ-NGT", "L83V-TTH"]], "fams_fid": [], "famc_num": [4], "fams_num": [], "given": "Frank", "surname": "Kennedy", "gender": "M", "birtdate": "       1856", "birtplac": "Canada West", "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 61, "fid": "MT5X-QH3", "famc_fid": [["LCVQ-NGT", "L83V-TTH"]], "fams_fid": [], "famc_num": [4], "fams_num": [], "given": "Thomas", "surname": "Kennedy", "gender": "M", "birtdate": "       1859", "birtplac": "Canada West", "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 62, "fid": "LC2H-7NZ", "famc_fid": [["LCVQ-NGT", "L83V-TTH"]], "fams_fid": [["LC2H-7NZ", "LC26-1DD"]], "famc_num": [4], "fams_num": [61], "given": "William", "surname": "Kennedy", "gender": "M", "birtdate": "       1860", "birtplac": "Canada West", "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": [["LC2H-7NZ", "LC26-1DD", "MQBB-47N"]]}
{"num": 63, "fid": "9KDW-59P", "famc_fid": [["LZ38-WH7", "LZ38-WHX"]], "fams_fid": [], "famc_num": [7], "fams_num": [], "given": "Charles M.", "surname": "Hickey", "gender": "M", "birtdate": "ABT 1859", "birtplac": "Boston, Suffolk, Massachusetts, United States", "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 64, "fid": "9KDW-59B", "famc_fid": [["LZ38-WH7", "LZ38-WHX"]], "fams_fid": [], "famc_num": [7], "fams_num": [], "given": "Margaret", "surname": "Hickey", "gender": "F", "birtdate": "ABT 1860", "birtplac": "Boston, Suffolk, Massachusetts, United States", "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 65, "fid": "9KDW-5S3", "famc_fid": [["LZ38-WH7", "LZ38-WHX"]], "fams_fid": [], "famc_num": [7], "fams_num": [], "given": "James F.", "surname": "Hickey", "gender": "M", "birtdate": "ABT 1861", "birtplac": "Boston, Suffolk, Massachusetts, United States", "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 66, "fid": "L7W4-PTV", "famc_fid": [["LZ38-WH7", "LZ38-WHX"]], "fams_fid": [], "famc_num": [7], "fams_num": [], "given": "John", "surname": "Hickey", "gender": "M", "birtdate": "9 Jan 1866", "birtplac": "Boston, Suffolk, Massachusetts", "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 67, "fid": "LBKC-HY5", "famc_fid": [["KPQB-B7X", null]], "fams_fid": [], "famc_num": [16], "fams_num": [], "given": "Mary Anne", "surname": "FitzGerald", "gender": "F", "birtdate": "1834", "birtplac": null, "deatdate": "1904", "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 68, "fid": "LHTZ-LKY", "famc_fid": [["LV7R-QM8", "L83V-TTZ"]], "fams_fid": [], "famc_num": [3], "fams_num": [], "given": "Mary Ethel", "surname": "Fitzgerald", "gender": "F", "birtdate": "13Oct1890", "birtplac": "Boston, Suffolk, Massachusetts", "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 69, "fid": "KG83-BL5", "famc_fid": [["LV7R-QM8", "L83V-TTZ"]], "fams_fid": [], "famc_num": [3], "fams_num": [], "given": "Mary Agnes", "surname": "Fitzgerald", "gender": "F", "birtdate": "13 Nov 1892", "birtplac": "Boston, Suffock County, Massachusetts", "deatdate": "       1936", "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 70, "fid": "LWRR-VRV", "famc_fid": [["LV7R-QM8", "L83V-TTZ"]], "fams_fid": [["L8BM-8Z7", "LWRR-VRV"]], "famc_num": [3], "fams_num": [27], "given": "Martha", "surname": "Fitzgerald", "gender": "F", "birtdate": "Mar 1893", "birtplac": "Massachusetts", "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": [["L8BM-8Z7", "LWRR-VRV", "MK7X-BT4"]]}
{"num": 71, "fid": "LTC6-2SD", "famc_fid": [["LV7R-QM8", "L83V-TTZ"]], "fams_fid": [], "famc_num": [3], "fams_num": [], "given": "Paul", "surname": "Fitzgerald", "gender": "M", "birtdate": "1894", "birtplac": "Massachusetts, United States", "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 72, "fid": "MK43-JTP", "famc_fid": [["LV7R-QM8", "L83V-TTZ"]], "fams_fid": [["MK43-JTP", "LBM5-X4L"], ["MK43-JTP", "9KDW-PLN"]], "famc_num": [3], "fams_num": [36, 37], "given": "Thomas Acton", "surname": "Fitzgerald", "gender": "M", "birtdate": "19 APR 1895", "birtplac": "Boston, Suffolk, Massachusetts, United States", "deatdate": "September 1968", "deatplac": null, "chrdate": null, "chrplac": null, "buridate": "1968", "buriplac": "West Roxbury, Suffolk, Massachusetts, United States of America", "parents": null, "children": null, "spouses": [["MK43-JTP", "9KDW-PLN", "MKK5-XFJ"], ["MK43-JTP", "LBM5-X4L", "MKKR-Z6P"]]}
{"num": 73, "fid": "LDXR-7MW", "famc_fid": [["LV7R-QM8", "L83V-TTZ"]], "fams_fid": [["LDXR-7MH", "LDXR-7MW"]], "famc_num": [3], "fams_num": [26], "given": "Julia", "surname": "Fitzgerald", "gender": "F", "birtdate": "Jan 1896", "birtplac": "Massachusetts", "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": [["LDXR-7MH", "LDXR-7MW", "M65Q-8PH"]]}
{"num": 74, "fid": "9JZ6-8Z3", "famc_fid": [["LV7R-QM8", "L83V-TTZ"]], "fams_fid": [], "famc_num": [3], "fams_num": [], "given": "Frances", "surname": "Fitzgerald", "gender": "F", "birtdate": "25 Jun 1896", "birtplac": "Boston, Suffolk, Massachusetts", "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 75, "fid": "9JG2-46T", "famc_fid": [["LV7R-QM8", "L83V-TTZ"]], "fams_fid": [["9JG2-46T", "966S-VS2"]], "famc_num": [3], "fams_num": [28], "given": "John Francis", "surname": "Fitzgerald", "gender": "M", "birtdate": "2 Aug 1896", "birtplac": "Boston, Suffolk, Massachusetts", "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": [["9JG2-46T", "966S-VS2", "MJW8-GFK"]]}
{"num": 76, "fid": "LTQX-6CK", "famc_fid": [["LV7R-QM8", "L83V-TTZ"]], "fams_fid": [["LTQX-K2P", "LTQX-6CK"]], "famc_num": [3], "fams_num": [49], "given": "Anna M", "surname": "Fitzgerald", "gender": "F", "birtdate": "1897", "birtplac": "Massachusetts", "deatdate": "19 Jan 2004", "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": [["LTQX-K2P", "LTQX-6CK", "MV2N-YC7"]]}
{"num": 77, "fid": "LWLT-LFR", "famc_fid": [["LV7R-QM8", "L83V-TTZ"]], "fams_fid": [["LWLT-LFR", "LWLT-LFL"]], "famc_num": [3], "fams_num": [54], "given": "John Francis", "surname": "Fitzgerald", "gender": "M", "birtdate": "07 Dec 1897", "birtplac": "Concord, Massachusetts", "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": [["LWLT-LFR", "LWLT-LFL", "M8GP-WPL"]]}
{"num": 78, "fid": "LTC6-KVZ", "famc_fid": [["LV7R-QM8", "L83V-TTZ"]], "fams_fid": [["LTC6-KVZ", "K26Z-KQX"]], "famc_num": [3], "fams_num": [32], "given": "William H", "surname": "Fitzgerald", "gender": "M", "birtdate": "Dec 1897", "birtplac": "Massachusetts, United States", "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": [["LTC6-KVZ", "K26Z-KQX", "MVYG-CLH"]]}
{"num": 79, "fid": "LTC6-V7K", "famc_fid": [["LV7R-QM8", "L83V-TTZ"]], "fams_fid": [], "famc_num": [3], "fams_num": [], "given": "Katharine L", "surname": "Fitzgerald", "gender": "F", "birtdate": "1899", "birtplac": "Massachusetts, United States", "deatdate": "22 Sep 1993", "deatplac": "Cambridge, Middlesex, Massachusetts", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 80, "fid": "M32B-9WM", "famc_fid": [["LV7R-QM8", "L83V-TTZ"]], "fams_fid": [], "famc_num": [3], "fams_num": [], "given": "Eunice", "surname": "Fitzgerald", "gender": "F", "birtdate": "       1900", "birtplac": "Boston, Suffolk, Massachusetts", "deatdate": "       1923", "deatplac": null, "chrdate": null, "chrplac": null, "buridate": "1923", "buriplac": "West Roxbury, Suffolk, Massachusetts, United States of America", "parents": null, "children": null, "spouses": null}
{"num": 81, "fid": "MD9D-QV4", "famc_fid": [["LV7R-QM8", "L83V-TTZ"]], "fams_fid": [], "famc_num": [3], "fams_num": [], "given": "Frederick", "surname": "Fitzgerald", "gender": "M", "birtdate": "       1904", "birtplac": "Boston, Suffolk, Massachusetts", "deatdate": "       1935", "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 82, "fid": "L78G-MWH", "famc_fid": [["LRG3-FJ2", "LRG3-F98"]], "fams_fid": [["L78G-MWH", "M59D-3ZT"], ["L78G-MWH", "KGMB-X4H"]], "famc_num": [10], "fams_num": [24, 23], "given": "John", "surname": "Kennedy", "gender": "M", "birtdate": "1804", "birtplac": "Wexford, Ireland", "deatdate": "1864", "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": [["L78G-MWH", "KGMB-X4H", "MML9-5G2"], ["L78G-MWH", "M59D-3ZT", "MQ6J-TVT"]]}
{"num": 83, "fid": "KPW9-YJY", "famc_fid": [["LRG3-FJ2", "LRG3-F98"]], "fams_fid": [["KPW9-YJY", "M59D-3H1"]], "famc_num": [10], "fams_num": [25], "given": "James", "surname": "Kennedy", "gender": "M", "birtdate": "1816", "birtplac": "Dunganstown, County Wexford, Ireland", "deatdate": "1881", "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": [["KPW9-YJY", "M59D-3H1", "MQ6J-KXJ"]]}
{"num": 84, "fid": "LRG3-2BN", "famc_fid": [["LRG3-FJ2", "LRG3-F98"]], "fams_fid": [["LRG3-5HF", "LRG3-2BN"]], "famc_num": [10], "fams_num": [22], "given": "Mary", "surname": "Kennedy", "gender": "F", "birtdate": "1820", "birtplac": "Ireland", "deatdate": "1898", "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": [["LRG3-5HF", "LRG3-2BN", "MV6Y-8TC"]]}
{"num": 85, "fid": "LYC7-WSH", "famc_fid": [["LRG3-FJ2", "LRG3-F98"]], "fams_fid": [["LYC7-WSH", "LYC7-6SW"]], "famc_num": [10], "fams_num": [42], "given": "William", "surname": "Kennedy", "gender": "M", "birtdate": "15 March 1826", "birtplac": "Dunganstown, County Wexford, Ireland", "deatdate": "19 December 1900", "deatplac": "Harrisville, Lewis, New York, United States", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": [["LYC7-WSH", "LYC7-6SW", "MKH5-C5L"]]}
{"num": 86, "fid": "LKL8-VJ9", "famc_fid": [["MVFK-TQP", "MVFK-TWD"]], "fams_fid": [], "famc_num": [6], "fams_num": [], "given": "Ellen Augusta", "surname": "Hannon", "gender": "F", "birtdate": "1856", "birtplac": null, "deatdate": "1928", "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 87, "fid": "LVDF-8XR", "famc_fid": [["MVFK-TQP", "MVFK-TWD"]], "fams_fid": [], "famc_num": [6], "fams_num": [], "given": "Nellie A", "surname": "Hannon", "gender": "F", "birtdate": "1857", "birtplac": "MA", "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 88, "fid": "K4V4-MQR", "famc_fid": [["MVFK-TQP", "MVFK-TWD"]], "fams_fid": [], "famc_num": [6], "fams_num": [], "given": "Edmond Fitz", "surname": "Hannon", "gender": "M", "birtdate": "       1858", "birtplac": "Of,Acton,Middlesex,Massachusetts", "deatdate": "       1865", "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 89, "fid": "LVDF-8N5", "famc_fid": [["MVFK-TQP", "MVFK-TWD"]], "fams_fid": [], "famc_num": [6], "fams_num": [], "given": "Michael J", "surname": "Hannon", "gender": "M", "birtdate": "1861", "birtplac": "MA", "deatdate": "21 Oct 1881", "deatplac": "Boston, Massachusetts", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 90, "fid": "MJSF-TX1", "famc_fid": [["MVFK-TQP", "MVFK-TWD"]], "fams_fid": [], "famc_num": [6], "fams_num": [], "given": "James", "surname": "Hannon", "gender": "M", "birtdate": "       1863", "birtplac": "Acton,Middlesex,Massachusetts", "deatdate": "       1889", "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": "Concord, Massachusetts", "parents": null, "children": null, "spouses": null}
{"num": 91, "fid": "MJS6-8MQ", "famc_fid": [["MVFK-TQP", "MVFK-TWD"]], "fams_fid": [], "famc_num": [6], "fams_num": [], "given": "Emily Gertrude", "surname": "Hannon", "gender": "F", "birtdate": "       1867", "birtplac": "Acton,Middlesex,Massachusetts", "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 92, "fid": "KGW2-2P9", "famc_fid": [["MVFK-TQP", "MVFK-TWD"]], "fams_fid": [], "famc_num": [6], "fams_num": [], "given": "Lizzie", "surname": "Hammon", "gender": "F", "birtdate": "17 Dec 1869", "birtplac": "Acton, Middlesex, Massachusetts", "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 93, "fid": "LB3F-SQG", "famc_fid": [["MVFK-TQP", "MVFK-TWD"]], "fams_fid": [], "famc_num": [6], "fams_num": [], "given": "Elizabeth", "surname": "Hannon", "gender": "F", "birtdate": "1870", "birtplac": "Acton, Mass.", "deatdate": "09 Dec 1873", "deatplac": "Acton, Massachusetts", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 94, "fid": "MJSX-84F", "famc_fid": [["MVFK-TQP", "MVFK-TWD"]], "fams_fid": [["MJSX-84F", "LYLZ-JW7"]], "famc_num": [6], "fams_num": [43], "given": "John Edmond", "surname": "Hannon", "gender": "M", "birtdate": "       1877", "birtplac": "Acton,Middlesex,Massachusetts", "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": [["MJSX-84F", "LYLZ-JW7", "MKF7-X5G"]]}
{"num": 95, "fid": "LZNR-G97", "famc_fid": [], "fams_fid": [["L89N-K6Q", "LZNR-G97"]], "famc_num": [], "fams_num": [17], "given": "Jaqueline", "surname": "Bouvier", "gender": "F", "birtdate": "28 Jul 1929", "birtplac": "Southampton, New York", "deatdate": "19 May 1994", "deatplac": "New York, New York", "chrdate": null, "chrplac": "New York City, New York, United States", "buridate": "       1993", "buriplac": "Arlington Nat Cem, Virginia", "parents": null, "children": null, "spouses": [["L89N-K6Q", "LZNR-G97", "M6XV-PSW"]]}
{"num": 96, "fid": "L89N-KNJ", "famc_fid": [["L89N-K6Q", "LZNR-G97"]], "fams_fid": [], "famc_num": [17], "fams_num": [], "given": "Infant Daughter", "surname": "Kennedy", "gender": "F", "birtdate": "23 August 1956", "birtplac": "Newport, Newport, Rhode Island, United States", "deatdate": "23 August 1956", "deatplac": "Newport, Newport, Rhode Island, United States", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": "Arlington, Arlington, Virginia, United States", "parents": null, "children": null, "spouses": null}
{"num": 97, "fid": "L89N-K6N", "famc_fid": [["L89N-K6Q", "LZNR-G97"]], "fams_fid": [["L89N-K6N", "L87K-QTV"]], "famc_num": [17], "fams_num": [29], "given": "John Fitzgerald", "surname": "Kennedy", "gender": "M", "birtdate": "25 November 1960", "birtplac": "Washington, District of Columbia, United States", "deatdate": "16 July 1999", "deatplac": null, "chrdate": "ABT 1960", "chrplac": null, "buridate": "22 Jul 1999", "buriplac": "At Sea Off Martha's Vinyard, Dukes, Massachusetts, USA", "parents": null, "children": null, "spouses": [["L89N-K6N", "L87K-QTV", "M6WK-Q1C"]]}
{"num": 98, "fid": "LZNR-GF4", "famc_fid": [["L89N-K6Q", "LZNR-G97"]], "fams_fid": [], "famc_num": [17], "fams_num": [], "given": "Patrick Bouvier", "surname": "Kennedy", "gender": "M", "birtdate": "7 August 1963", "birtplac": "Bourne, Massachusetts", "deatdate": "8 August 1963", "deatplac": "Boston, Suffolk, Massachusetts, United States", "chrdate": null, "chrplac": null, "buridate": "August 1963", "buriplac": "Arlington National Cemetery, Arlington, Virginia, United States", "parents": null, "children": null, "spouses": null}
{"num": 99, "fid": "LHRR-LWW", "famc_fid": [], "fams_fid": [["LYR1-P2V", "LHRR-LWW"], ["9VHB-NT4", "LHRR-LWW"], ["LR4T-VLN", "LHRR-LWW"], ["LWF8-N1V", "LHRR-LWW"], ["LZT8-TDL", "LHRR-LWW"], ["L89N-K6J", "LHRR-LWW"]], "famc_num": [], "fams_num": [44, 45, 46, 47, 48, 18], "given": "Margaret", "surname": "Carnegie", "gender": "F", "birtdate": "11 June 1872", "birtplac": "Pittsburgh, Allegheny, Pennsylvania, United States", "deatdate": "8 October 1927", "deatplac": "Delaware, Philadelphia, Pennsylvania, United States", "chrdate": "28 March 1901", "chrplac": "Christ Church Of Frederica, St. Simons Island, Glynn, Georgia", "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": [["LWF8-N1V", "LHRR-LWW", "MZHV-Z8Y"], ["LYR1-P2V", "LHRR-LWW", "MKJD-XZF"], ["LZT8-TDL", "LHRR-LWW", "MKD6-QQB"], ["L89N-K6J", "LHRR-LWW", "MKD8-D44"], ["9VHB-NT4", "LHRR-LWW", "MVN6-S11"], ["LR4T-VLN", "LHRR-LWW", "MVZQ-71Z"]]}
{"num": 100, "fid": "LYFL-XPN", "famc_fid": [["L89N-K6J", "LYF5-P97"], ["L89N-K6J", "LHRR-LWW"]], "fams_fid": [["LYFL-JM4", "LYFL-XPN"]], "famc_num": [18, 19], "fams_num": [31], "given": "Helen \"Hedy\"", "surname": "Kennedy", "gender": "F", "birtdate": "1909", "birtplac": "Scatter Branch, Hunt, Texas, United States", "deatdate": "26 July 1987", "deatplac": "Brownwood, Brown, Texas, United States", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": [["LYFL-JM4", "LYFL-XPN", "MKDZ-1BL"]]}
{"num": 101, "fid": "LYF5-P97", "famc_fid": [], "fams_fid": [["L89N-K6J", "LYF5-P97"]], "famc_num": [], "fams_num": [19], "given": "Lora Grimmett", "surname": "McAllister", "gender": "F", "birtdate": null, "birtplac": null, "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": [["L89N-K6J", "LYF5-P97", "MKD6-72T"]]}
{"num": 102, "fid": "LHDK-RKJ", "famc_fid": [], "fams_fid": [["LHDK-RKJ", "K6S9-BCF"]], "famc_num": [], "fams_num": [20], "given": "Charles", "surname": "Burke", "gender": "M", "birtdate": "23 AUG 1899", "birtplac": "Medford, Middlesex Co, Ma", "deatdate": "5 APR 1967", "deatplac": "Boston, Suffolk Co, MA", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": "Winthrop, Suffolk Co, MA", "parents": null, "children": null, "spouses": null}
{"num": 103, "fid": "LYPF-3BS", "famc_fid": [], "fams_fid": [["LYPF-3BS", "K6S9-BCF"]], "famc_num": [], "fams_num": [21], "given": "Charles test", "surname": "Burke", "gender": "M", "birtdate": "BC 1900", "birtplac": null, "deatdate": null, "deatplac": null, "chrdate": "1900 BC", "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 104, "fid": "LRG3-5HF", "famc_fid": [], "fams_fid": [["LRG3-5HF", "LRG3-2BN"]], "famc_num": [], "fams_num": [22], "given": "James", "surname": "Molloy", "gender": "M", "birtdate": null, "birtplac": null, "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 105, "fid": "KGMB-X4H", "famc_fid": [], "fams_fid": [["L78G-MWH", "KGMB-X4H"]], "famc_num": [], "fams_num": [23], "given": "Margaret", "surname": "Parden", "gender": "F", "birtdate": "<1813>", "birtplac": "<,, Ireland>", "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 106, "fid": "M59D-3ZT", "famc_fid": [], "fams_fid": [["L78G-MWH", "M59D-3ZT"]], "famc_num": [], "fams_num": [24], "given": "Mary", "surname": "Gunnip", "gender": "F", "birtdate": "1816", "birtplac": "Ireland", "deatdate": "1881", "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 107, "fid": "M59D-3H1", "famc_fid": [], "fams_fid": [["KPW9-YJY", "M59D-3H1"]], "famc_num": [], "fams_num": [25], "given": "Catherine", "surname": "Colfer", "gender": "F", "birtdate": "       1819", "birtplac": "Ireland", "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 108, "fid": "LDXR-7MH", "famc_fid": [], "fams_fid": [["LDXR-7MH", "LDXR-7MW"]], "famc_num": [], "fams_num": [26], "given": "Hugh", "surname": "O'Connor", "gender": "M", "birtdate": "1830", "birtplac": null, "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 109, "fid": "L8BM-8Z7", "famc_fid": [], "fams_fid": [["L8BM-8Z7", "LWRR-VRV"]], "famc_num": [], "fams_num": [27], "given": "Dennis Alphonso", "surname": "Lyons", "gender": "M", "birtdate": "2 Sep 1875", "birtplac": "Ireland", "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 110, "fid": "966S-VS2", "famc_fid": [], "fams_fid": [["9JG2-46T", "966S-VS2"]], "famc_num": [], "fams_num": [28], "given": "Catharine", "surname": "Fitzgerald", "gender": "F", "birtdate": "1851", "birtplac": null, "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 111, "fid": "L87K-QTV", "famc_fid": [], "fams_fid": [["L89N-K6N", "L87K-QTV"]], "famc_num": [], "fams_num": [29], "given": "Carolyn Jeanne", "surname": "Bessette", "gender": "F", "birtdate": "7 January 1966", "birtplac": "White Plains, Westchester, New York, United States", "deatdate": "16 July 1999", "deatplac": "at sea, offshore Gay Hea, Dukes ,MA", "chrdate": null, "chrplac": null, "buridate": "22 JUL 1999", "buriplac": "At sea, from deck of USS Briscoe near Martha's Vineyard, MA.", "parents": null, "children": null, "spouses": null}
{"num": 112, "fid": "LHX8-48T", "famc_fid": [], "fams_fid": [["LHX8-48T", "LHX8-4DQ"]], "famc_num": [], "fams_num": [30], "given": "Charles", "surname": "Williaims", "gender": "M", "birtdate": "       1846", "birtplac": "Sweden", "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 113, "fid": "LYFL-JM4", "famc_fid": [], "fams_fid": [["LYFL-JM4", "LYFL-XPN"]], "famc_num": [], "fams_num": [31], "given": "George Amon", "surname": "Lee", "gender": "M", "birtdate": null, "birtplac": null, "deatdate": "1946", "deatplac": "Brownwood, Brown, Texas, United States", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 114, "fid": "K26Z-KQX", "famc_fid": [], "fams_fid": [["LTC6-KVZ", "K26Z-KQX"]], "famc_num": [], "fams_num": [32], "given": "Lillian", "surname": "Anderson", "gender": "F", "birtdate": "1877", "birtplac": null, "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 115, "fid": "LK33-F5K", "famc_fid": [], "fams_fid": [["LK33-F5K", "MT5X-Q72"]], "famc_num": [], "fams_num": [33], "given": "John", "surname": "Burnley", "gender": "M", "birtdate": "about 1850", "birtplac": "Canada", "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 116, "fid": "LW4X-TYN", "famc_fid": [], "fams_fid": [["LW4X-TYN", "LH6W-6YM"]], "famc_num": [], "fams_num": [34], "given": "John Thomas", "surname": "Caufield", "gender": "M", "birtdate": "   JAN 1861", "birtplac": "Weymouth, Norfolk Co, Ma", "deatdate": "12 JUL 1937", "deatplac": "Lynn, Essex Co, Ma", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": "Malden, Middlesex Co, Ma", "parents": null, "children": null, "spouses": null}
{"num": 117, "fid": "KP7W-L4X", "famc_fid": [], "fams_fid": [["LZNR-GRZ", "KP7W-L4X"]], "famc_num": [], "fams_num": [35], "given": "Ethel", "surname": "Skakel", "gender": "F", "birtdate": "11 APR 1928", "birtplac": "Chicago, Cook, Illinois, United States", "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 118, "fid": "9KDW-PLN", "famc_fid": [], "fams_fid": [["MK43-JTP", "9KDW-PLN"]], "famc_num": [], "fams_num": [36], "given": "Marion D.", "surname": "Reardon", "gender": "F", "birtdate": "about 1897", "birtplac": "Boston, Suffolk, Massachusetts, United States", "deatdate": "28 February 1925", "deatplac": "Boston, Suffolk, Massachusetts, United States", "chrdate": null, "chrplac": null, "buridate": "1925", "buriplac": "West Roxbury, Suffolk, Massachusetts, United States of America", "parents": null, "children": null, "spouses": null}
{"num": 119, "fid": "LBM5-X4L", "famc_fid": [], "fams_fid": [["MK43-JTP", "LBM5-X4L"]], "famc_num": [], "fams_num": [37], "given": "Bernice", "surname": "Unknown", "gender": "F", "birtdate": "1907", "birtplac": "Massachusetts", "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 120, "fid": "L83V-TTD", "famc_fid": [], "fams_fid": [["L83V-TTD", "LZNR-GGF"]], "famc_num": [], "fams_num": [38], "given": "William John Robert", "surname": "Cavendish", "gender": "M", "birtdate": "10 December 1917", "birtplac": "England, United Kingdom", "deatdate": "10 September 1944", "deatplac": "Heppen, Leopoldsburg, Limburg, Belgium", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 121, "fid": "K8YS-D2Y", "famc_fid": [], "fams_fid": [["K8YS-D2Y", "KGK2-SFX"]], "famc_num": [], "fams_num": [39], "given": "Charles Humphrey", "surname": "Mahoney", "gender": "M", "birtdate": "12 Dec 1847", "birtplac": "Boston, Middlesex, Massachusetts, USA", "deatdate": "25 AUG 1928", "deatplac": "Saratoga Springs, Saratoga Co, NY", "chrdate": null, "chrplac": null, "buridate": "AUG 1928", "buriplac": "Malden,Middlesex Co,MA", "parents": null, "children": null, "spouses": null}
{"num": 122, "fid": "L89N-KXS", "famc_fid": [], "fams_fid": [["L89N-KXS", "LRF8-G8C"]], "famc_num": [], "fams_num": [40], "given": "Peter Sydney", "surname": "Lawford", "gender": "M", "birtdate": "7 September 1923", "birtplac": "City of London, England, United Kingdom", "deatdate": "24 December 1984", "deatplac": "Cedars-Sinai Medical Center in Los Angeles, California, United States", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": "Ashes were removed in 1988 from Westwood Village Memorial Park Cemetery and scattered into the Pacific Ocean", "parents": null, "children": null, "spouses": null}
{"num": 123, "fid": "LRFD-48Z", "famc_fid": [], "fams_fid": [["LRFD-48Z", "LJL3-M17"]], "famc_num": [], "fams_num": [41], "given": "Robert Sargent", "surname": "Shriver Jr", "gender": "M", "birtdate": "9 Nov 1915", "birtplac": "Westminster, Carroll, Maryland, USA", "deatdate": "January 18, 2011", "deatplac": "Suburban Hospital - Bethesda, MD", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": "Centerville, Barnstable, Barnstable, Massachusetts, United States", "parents": null, "children": null, "spouses": null}
{"num": 124, "fid": "LYC7-6SW", "famc_fid": [], "fams_fid": [["LYC7-WSH", "LYC7-6SW"]], "famc_num": [], "fams_num": [42], "given": "Susannah", "surname": "Fisher", "gender": "F", "birtdate": "21 December 1836", "birtplac": "Watertown, Jefferson, New York, United States", "deatdate": "19 March 1910", "deatplac": "Harrisville, Lewis, New York, United States", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 125, "fid": "LYLZ-JW7", "famc_fid": [], "fams_fid": [["MJSX-84F", "LYLZ-JW7"]], "famc_num": [], "fams_num": [43], "given": "Lenora A", "surname": "Hurley", "gender": "F", "birtdate": "1887", "birtplac": "Mansfield, Bristol, Massachusetts, United States", "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 126, "fid": "LWF8-N1V", "famc_fid": [], "fams_fid": [["LWF8-N1V", "LHRR-LWW"]], "famc_num": [], "fams_num": [44], "given": "Oliver Garrison", "surname": "Ricketson", "gender": "M", "birtdate": "15 Oct 1864", "birtplac": "Pittsburgh,, PA", "deatdate": "16 Mar 1943", "deatplac": "Washington, DC, USA", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 127, "fid": "LYR1-P2V", "famc_fid": [], "fams_fid": [["LYR1-P2V", "LHRR-LWW"]], "famc_num": [], "fams_num": [45], "given": "William Henry", "surname": "Lee", "gender": "M", "birtdate": null, "birtplac": null, "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 128, "fid": "LZT8-TDL", "famc_fid": [], "fams_fid": [["LZT8-TDL", "LHRR-LWW"]], "famc_num": [], "fams_num": [46], "given": "William Henry Fitzhugh \"Rooney\"", "surname": "Lee", "gender": "M", "birtdate": "31 May 1837", "birtplac": "Arlington, Virginia, United States", "deatdate": "15 October 1891", "deatplac": "Ravensworth, Fairfax, Virginia, United States", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": "Lee Chapel, Lexiington, Albemarle, Virgiinia", "parents": null, "children": null, "spouses": null}
{"num": 129, "fid": "9VHB-NT4", "famc_fid": [], "fams_fid": [["9VHB-NT4", "LHRR-LWW"]], "famc_num": [], "fams_num": [47], "given": "William Ellsworth", "surname": "Lee", "gender": "M", "birtdate": "31 January 1867", "birtplac": "Petroleum, Ritchie, West Virginia, United States", "deatdate": "28 October 1936", "deatplac": "Houston, Harris, Texas, United States", "chrdate": null, "chrplac": null, "buridate": "1936", "buriplac": "Houston, Harris, Texas, United States of America", "parents": null, "children": null, "spouses": null}
{"num": 130, "fid": "LR4T-VLN", "famc_fid": [], "fams_fid": [["LR4T-VLN", "LHRR-LWW"]], "famc_num": [], "fams_num": [48], "given": "Edmund Fitzgerald", "surname": "Hutton", "gender": "M", "birtdate": null, "birtplac": null, "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 131, "fid": "LTQX-K2P", "famc_fid": [], "fams_fid": [["LTQX-K2P", "LTQX-6CK"]], "famc_num": [], "fams_num": [49], "given": "Edward F", "surname": "McLeod", "gender": "M", "birtdate": "5 ao\u00fbt 1922", "birtplac": "Boston, Suffolk, Massachusetts, \u00c9tats-Unis d'Am\u00e9rique", "deatdate": "15 avril 2014", "deatplac": "Randolph, Massachusetts, \u00c9tats-Unis d'Am\u00e9rique", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": "Randolph, Massachusetts, \u00c9tats-Unis d'Am\u00e9rique", "parents": null, "children": null, "spouses": null}
{"num": 132, "fid": "KGW2-2P4", "famc_fid": [], "fams_fid": [["MVFK-TQP", "KGW2-2P4"]], "famc_num": [], "fams_num": [50], "given": "Mary A", "surname": "Fitzgerald", "gender": "F", "birtdate": null, "birtplac": null, "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 133, "fid": "K6WT-NWT", "famc_fid": [], "fams_fid": [["K6WT-NWT", "KZ2X-SKM"]], "famc_num": [], "fams_num": [51], "given": "Lawrence", "surname": "Kane", "gender": "M", "birtdate": "29 NOV 1858", "birtplac": "Wexford Co, Ireland", "deatdate": "19 JUL 1905", "deatplac": "East Boston, Suffolk Co, Ma", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": "Malden, Middlesex Co, Ma", "parents": null, "children": null, "spouses": null}
{"num": 134, "fid": "LJ19-331", "famc_fid": [], "fams_fid": [["LJ19-331", "KP7V-FMM"]], "famc_num": [], "fams_num": [52], "given": "Michael", "surname": "Fitzgerald", "gender": "M", "birtdate": "BET 1795 AND 1797", "birtplac": "Bruff, 5310, Ireland", "deatdate": "1848", "deatplac": "Dunganstown, Wexford, Ireland", "chrdate": null, "chrplac": null, "buridate": "24 Dec 1848", "buriplac": "St Mary, Lambeth, England", "parents": null, "children": null, "spouses": null}
{"num": 135, "fid": "KLLY-TXP", "famc_fid": [], "fams_fid": [["KLLY-TXP", "KP7V-FMM"]], "famc_num": [], "fams_num": [53], "given": "Edmund", "surname": "FitzGerald", "gender": "M", "birtdate": "11 June 1750", "birtplac": "Amelia, Virginia, United States", "deatdate": "1818", "deatplac": "Leinster House, Amelia, Virginia, USA", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 136, "fid": "LWLT-LFL", "famc_fid": [], "fams_fid": [["LWLT-LFR", "LWLT-LFL"]], "famc_num": [], "fams_num": [54], "given": "Annie Theresa", "surname": "Sullivan", "gender": "F", "birtdate": "1878", "birtplac": null, "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 137, "fid": "L23M-G3Q", "famc_fid": [], "fams_fid": [["L23M-G3Q", "L23M-LYV"]], "famc_num": [], "fams_num": [55], "given": "Patrick", "surname": "Kennedy", "gender": "M", "birtdate": "about 1830", "birtplac": "Ireland", "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 138, "fid": "9JK5-L2Y", "famc_fid": [], "fams_fid": [["L89N-K62", "9JK5-L2Y"]], "famc_num": [], "fams_num": [56], "given": "Mary A", "surname": "Unknown", "gender": "F", "birtdate": null, "birtplac": "Boston", "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 139, "fid": "KGWP-YKX", "famc_fid": [], "fams_fid": [["L89N-K62", "KGWP-YKX"]], "famc_num": [], "fams_num": [57], "given": "Maria", "surname": "Hickey", "gender": "F", "birtdate": "about 1840", "birtplac": "Limrick, Ireland", "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 140, "fid": "LVJ5-43Y", "famc_fid": [], "fams_fid": [["LZNR-GY3", "LVJ5-43Y"]], "famc_num": [], "fams_num": [58], "given": "Virginia Joan", "surname": "Bennett", "gender": "F", "birtdate": "2 September 1936", "birtplac": "New York City, New York, New York, United States", "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 141, "fid": "LLHG-514", "famc_fid": [], "fams_fid": [["LZNR-GY3", "LLHG-514"]], "famc_num": [], "fams_num": [59], "given": "Victoria Anne", "surname": "Reggie", "gender": "F", "birtdate": null, "birtplac": null, "deatdate": null, "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 142, "fid": "L6YW-FK4", "famc_fid": [], "fams_fid": [["L6YW-FK4", "L6YW-X59"]], "famc_num": [], "fams_num": [60], "given": "Henry", "surname": "Arland", "gender": "M", "birtdate": "1804", "birtplac": null, "deatdate": "1878", "deatplac": null, "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 143, "fid": "LC26-1DD", "famc_fid": [], "fams_fid": [["LC2H-7NZ", "LC26-1DD"]], "famc_num": [], "fams_num": [61], "given": "Elizabeth", "surname": "Hill", "gender": "F", "birtdate": "1868", "birtplac": "Belfast, Down, Ireland", "deatdate": "30 January 1904", "deatplac": "Belfast, Down, Ireland", "chrdate": null, "chrplac": null, "buridate": null, "buriplac": null, "parents": null, "children": null, "spouses": null}
{"num": 144, "fid": "K6MY-9V3", "famc_fid": [], "fams_fid": [["K6MY-9V3", "K6MQ-7TK"]], "famc_num": [], "fams_num": [62], "given": "George William", "surname": "Connelly", "gender": "M", "birtdate": "10 JUN 1898", "birtplac": "East Boston, Suffolk Co, Ma", "deatdate": "29 AUG 1971", "deatplac": "St. Augustine, St. Johns Co, Fl", "chrdate": null, "chrplac": null, "buridate": "1971", "buriplac": "Saint Augustine, St. Johns, Florida, United States of America", "parents": null, "children": null, "spouses": null}
{"num": 1, "husb_fid": "L89N-K6J", "wife_fid": "L89N-K6V", "husb_num": 2, "wife_num": 3, "fid": "M63P-9L8", "marrdate": "7 October 1914", "marrplac": "Boston, Suffolk, Massachusetts, United States", "chil_fid": ["L89N-K6Q", "LZNR-GY3", "LRF8-G8C", "LJL3-M17", "LZNR-GRZ", "LRF8-RKC", "LZNR-GGF", "LZNR-GPG"], "chil_num": [32, 1, 34, 35, 33, 28, 30, 31]}
{"num": 2, "husb_fid": "L89N-K62", "wife_fid": "L89N-K6L", "husb_num": 4, "wife_num": 5, "fid": "M63P-9LX", "marrdate": "23 September 1887", "marrplac": "Boston, Suffolk, Massachusetts, United States", "chil_fid": ["K8Z9-VJ6", "K6MQ-7TK", "L89N-K6J", "K6S9-BCF"], "chil_num": [40, 41, 2, 42]}
{"num": 3, "husb_fid": "LV7R-QM8", "wife_fid": "L83V-TTZ", "husb_num": 6, "wife_num": 7, "fid": "MNQ8-Q9L", "marrdate": "18 Sep 1889", "marrplac": "Boston, Suffolk, Massachusetts", "chil_fid": ["9JZ6-8Z3", "L89N-K6V", "KG83-BL5", "LTC6-KVZ", "MK43-JTP", "LTQX-6CK", "LTC6-V7K", "LDXR-7MW", "MD9D-QV4", "LWRR-VRV", "LTC6-2SD", "9JG2-46T", "LWLT-LFR", "M32B-9WM", "LHTZ-LKY"], "chil_num": [3, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81]}
{"num": 4, "husb_fid": "LCVQ-NGT", "wife_fid": "L83V-TTH", "husb_num": 8, "wife_num": 9, "fid": "MN9W-JXL", "marrdate": "26 September 1849", "marrplac": null, "chil_fid": ["MT5X-Q72", "MT5X-Q4Q", "LH6W-6YM", "L6YW-X59", "LRG3-41R", "LHX8-4DQ", "L89N-K62", "MT5X-QH3", "KZ2X-SKM", "KGK2-SFX", "LC2H-7NZ", "MT5X-Q4V", "MT5X-Q7Z"], "chil_num": [4, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62]}
{"num": 5, "husb_fid": "KCRN-GRR", "wife_fid": "LTVL-K2F", "husb_num": 10, "wife_num": 11, "fid": "MH9Y-B1B", "marrdate": null, "marrplac": "Boston, Suffolk, Mass, USA", "chil_fid": ["KP7V-FMM", "LV7R-QM8"], "chil_num": [49, 6]}
{"num": 6, "husb_fid": "MVFK-TQP", "wife_fid": "MVFK-TWD", "husb_num": 12, "wife_num": 13, "fid": "MKVB-PZC", "marrdate": "12 Feb 1854", "marrplac": "Boston, Suffolk, Massachusetts", "chil_fid": ["MJS6-8MQ", "KGW2-2P9", "LVDF-8XR", "LKL8-VJ9", "L83V-TTZ", "MJSF-TX1", "K4V4-MQR", "LB3F-SQG", "LVDF-8N5", "MJSX-84F"], "chil_num": [7, 86, 87, 88, 89, 90, 91, 92, 93, 94]}
{"num": 7, "husb_fid": "LZ38-WH7", "wife_fid": "LZ38-WHX", "husb_num": 14, "wife_num": 15, "fid": "MZLL-W4C", "marrdate": "ABT 1855", "marrplac": "Boston, Suffolk, Mass, USA", "chil_fid": ["9KDW-59B", "9KDW-5S3", "L7W4-PTV", "L89N-K6L", "9KDW-59P"], "chil_num": [64, 65, 66, 5, 63]}
{"num": 8, "husb_fid": "L7J2-S8N", "wife_fid": "L7J2-S6Z", "husb_num": 16, "wife_num": 17, "fid": "MC2X-SPB", "marrdate": "   AUG 1819", "marrplac": "Ireland", "chil_fid": ["MWHS-RYV", "LZ38-WH7", "MWHS-RB9", "MWHS-RYR", "MWHS-RYH", "MWHS-RB7"], "chil_num": [43, 44, 45, 46, 14, 47]}
{"num": 9, "husb_fid": "9KDW-R74", "wife_fid": "L6YW-F5M", "husb_num": 18, "wife_num": 19, "fid": "MNC2-FJ8", "marrdate": "Abt 1821", "marrplac": null, "chil_fid": ["L23M-LYV", "L83V-TTH"], "chil_num": [48, 9]}
{"num": 10, "husb_fid": "LRG3-FJ2", "wife_fid": "LRG3-F98", "husb_num": 20, "wife_num": 21, "fid": "MV6Y-HZ4", "marrdate": "1798", "marrplac": "Ireland", "chil_fid": ["KPW9-YJY", "LCVQ-NGT", "LRG3-2BN", "LYC7-WSH", "L78G-MWH"], "chil_num": [8, 82, 83, 84, 85]}
{"num": 11, "husb_fid": "KPQB-T8S", "wife_fid": "KPQB-THZ", "husb_num": 22, "wife_num": 23, "fid": "MHMK-LJM", "marrdate": "06 FEB 1825", "marrplac": null, "chil_fid": ["LZ38-WHX"], "chil_num": [15]}
{"num": 12, "husb_fid": "KPQB-B7X", "wife_fid": "KPQB-BZT", "husb_num": 24, "wife_num": 25, "fid": "MCPY-YZ3", "marrdate": "       1820", "marrplac": "Misc,Ireland", "chil_fid": ["LR37-61R", "LY17-M27", "LR37-WJJ", "MVFK-TWD", "LY1Q-N97"], "chil_num": [36, 37, 38, 39, 13]}
{"num": 13, "husb_fid": "KPQB-BJP", "wife_fid": "KHJW-61X", "husb_num": 26, "wife_num": 27, "fid": "MH9B-M14", "marrdate": "ABT 1820", "marrplac": ",, Ireland", "chil_fid": ["MVFK-TQP"], "chil_num": [12]}
{"num": 14, "husb_fid": null, "wife_fid": "L89N-K6V", "husb_num": null, "wife_num": 3, "fid": null, "marrdate": null, "marrplac": null, "chil_fid": ["LBKC-ZV5"], "chil_num": [29]}
{"num": 15, "husb_fid": "KCRN-GRR", "wife_fid": "K8G9-3WV", "husb_num": 10, "wife_num": 50, "fid": "MKGW-NWB", "marrdate": "1790", "marrplac": "Boston, Suffolk, Mass, USA", "chil_fid": ["KP7V-FMM"], "chil_num": [49]}
{"num": 16, "husb_fid": "KPQB-B7X", "wife_fid": null, "husb_num": 24, "wife_num": null, "fid": null, "marrdate": null, "marrplac": null, "chil_fid": ["LBKC-HY5"], "chil_num": [67]}
{"num": 17, "husb_fid": "L89N-K6Q", "wife_fid": "LZNR-G97", "husb_num": 1, "wife_num": 95, "fid": "M6XV-PSW", "marrdate": "<1950>", "marrplac": "Of Washinton, Usa", "chil_fid": ["L89N-K6N", "LZNR-GF4", "L89N-KNJ"], "chil_num": [96, 97, 98]}
{"num": 18, "husb_fid": "L89N-K6J", "wife_fid": "LHRR-LWW", "husb_num": 2, "wife_num": 99, "fid": "MKD8-D44", "marrdate": null, "marrplac": null, "chil_fid": ["LYFL-XPN"], "chil_num": [100]}
{"num": 19, "husb_fid": "L89N-K6J", "wife_fid": "LYF5-P97", "husb_num": 2, "wife_num": 101, "fid": "MKD6-72T", "marrdate": null, "marrplac": null, "chil_fid": ["LYFL-XPN"], "chil_num": [100]}
{"num": 20, "husb_fid": "LHDK-RKJ", "wife_fid": "K6S9-BCF", "husb_num": 102, "wife_num": 42, "fid": "M4VV-1RW", "marrdate": "14 JUN 1924", "marrplac": "Winthrop, Suffolk Co, MA", "chil_fid": [], "chil_num": []}
{"num": 21, "husb_fid": "LYPF-3BS", "wife_fid": "K6S9-BCF", "husb_num": 103, "wife_num": 42, "fid": "MKN7-RD6", "marrdate": null, "marrplac": null, "chil_fid": [], "chil_num": []}
{"num": 22, "husb_fid": "LRG3-5HF", "wife_fid": "LRG3-2BN", "husb_num": 104, "wife_num": 84, "fid": "MV6Y-8TC", "marrdate": null, "marrplac": null, "chil_fid": [], "chil_num": []}
{"num": 23, "husb_fid": "L78G-MWH", "wife_fid": "KGMB-X4H", "husb_num": 82, "wife_num": 105, "fid": "MML9-5G2", "marrdate": "       1828", "marrplac": "England", "chil_fid": [], "chil_num": []}
{"num": 24, "husb_fid": "L78G-MWH", "wife_fid": "M59D-3ZT", "husb_num": 82, "wife_num": 106, "fid": "MQ6J-TVT", "marrdate": "       1842", "marrplac": "Ireland", "chil_fid": [], "chil_num": []}
{"num": 25, "husb_fid": "KPW9-YJY", "wife_fid": "M59D-3H1", "husb_num": 83, "wife_num": 107, "fid": "MQ6J-KXJ", "marrdate": "1846", "marrplac": "Ireland", "chil_fid": [], "chil_num": []}
{"num": 26, "husb_fid": "LDXR-7MH", "wife_fid": "LDXR-7MW", "husb_num": 108, "wife_num": 73, "fid": "M65Q-8PH", "marrdate": "07 Dec 1853", "marrplac": "Chicopee, Hampden, Massachusetts", "chil_fid": [], "chil_num": []}
{"num": 27, "husb_fid": "L8BM-8Z7", "wife_fid": "LWRR-VRV", "husb_num": 109, "wife_num": 70, "fid": "MK7X-BT4", "marrdate": "12 Dec 1896", "marrplac": "Cambridge, Middlesex, Massachusetts", "chil_fid": [], "chil_num": []}
{"num": 28, "husb_fid": "9JG2-46T", "wife_fid": "966S-VS2", "husb_num": 75, "wife_num": 110, "fid": "MJW8-GFK", "marrdate": "14 Nov 1869", "marrplac": "Boston, Suffolk, Massachusetts, United States", "chil_fid": [], "chil_num": []}
{"num": 29, "husb_fid": "L89N-K6N", "wife_fid": "L87K-QTV", "husb_num": 97, "wife_num": 111, "fid": "M6WK-Q1C", "marrdate": "21 September 1996", "marrplac": "Cumberland Island, Camden, Georgia, United States", "chil_fid": [], "chil_num": []}
{"num": 30, "husb_fid": "LHX8-48T", "wife_fid": "LHX8-4DQ", "husb_num": 112, "wife_num": 58, "fid": "MMX8-X4H", "marrdate": "9 Jan 1874", "marrplac": "Peane Township, Michigan", "chil_fid": [], "chil_num": []}
{"num": 31, "husb_fid": "LYFL-JM4", "wife_fid": "LYFL-XPN", "husb_num": 113, "wife_num": 100, "fid": "MKDZ-1BL", "marrdate": null, "marrplac": null, "chil_fid": [], "chil_num": []}
{"num": 32, "husb_fid": "LTC6-KVZ", "wife_fid": "K26Z-KQX", "husb_num": 78, "wife_num": 114, "fid": "MVYG-CLH", "marrdate": "30 Dec 1902", "marrplac": "Lowell, Middlesex, Massachusetts", "chil_fid": [], "chil_num": []}
{"num": 33, "husb_fid": "LK33-F5K", "wife_fid": "MT5X-Q72", "husb_num": 115, "wife_num": 53, "fid": "MKGR-R45", "marrdate": "prior to 1874", "marrplac": "Ontario, Canada", "chil_fid": [], "chil_num": []}
{"num": 34, "husb_fid": "LW4X-TYN", "wife_fid": "LH6W-6YM", "husb_num": 116, "wife_num": 59, "fid": "M8JL-HC3", "marrdate": "21 Feb 1882", "marrplac": "Boston, Suffolk, Massachusetts", "chil_fid": [], "chil_num": []}
{"num": 35, "husb_fid": "LZNR-GRZ", "wife_fid": "KP7W-L4X", "husb_num": 34, "wife_num": 117, "fid": "MCPH-NN2", "marrdate": "17 JUN 1950", "marrplac": "Greenwich, Fairfield, Connecticut, United States", "chil_fid": [], "chil_num": []}
{"num": 36, "husb_fid": "MK43-JTP", "wife_fid": "9KDW-PLN", "husb_num": 72, "wife_num": 118, "fid": "MKK5-XFJ", "marrdate": " 7 SEP 1921", "marrplac": "Boston, Suffolk, Massachusetts, United States", "chil_fid": [], "chil_num": []}
{"num": 37, "husb_fid": "MK43-JTP", "wife_fid": "LBM5-X4L", "husb_num": 72, "wife_num": 119, "fid": "MKKR-Z6P", "marrdate": null, "marrplac": null, "chil_fid": [], "chil_num": []}
{"num": 38, "husb_fid": "L83V-TTD", "wife_fid": "LZNR-GGF", "husb_num": 120, "wife_num": 31, "fid": "MJLB-MSQ", "marrdate": "6 MAY 1944", "marrplac": "City of London, Middlesex, England, United Kingdom", "chil_fid": [], "chil_num": []}
{"num": 39, "husb_fid": "K8YS-D2Y", "wife_fid": "KGK2-SFX", "husb_num": 121, "wife_num": 55, "fid": "MJL6-GY6", "marrdate": "22 SEP 1872", "marrplac": "Boston,Suffolk,Massachusetts", "chil_fid": [], "chil_num": []}
{"num": 40, "husb_fid": "L89N-KXS", "wife_fid": "LRF8-G8C", "husb_num": 122, "wife_num": 33, "fid": "MVDB-NVR", "marrdate": "24 April 1954", "marrplac": null, "chil_fid": [], "chil_num": []}
{"num": 41, "husb_fid": "LRFD-48Z", "wife_fid": "LJL3-M17", "husb_num": 123, "wife_num": 32, "fid": "M2MF-YWN", "marrdate": "23 May 1953", "marrplac": "New York City, New York, United States", "chil_fid": [], "chil_num": []}
{"num": 42, "husb_fid": "LYC7-WSH", "wife_fid": "LYC7-6SW", "husb_num": 85, "wife_num": 124, "fid": "MKH5-C5L", "marrdate": "18 February 1855", "marrplac": "Carthage, Jefferson, New York, United States", "chil_fid": [], "chil_num": []}
{"num": 43, "husb_fid": "MJSX-84F", "wife_fid": "LYLZ-JW7", "husb_num": 94, "wife_num": 125, "fid": "MKF7-X5G", "marrdate": "26 Dec 1912", "marrplac": "Lexington, , Massachusetts, United States", "chil_fid": [], "chil_num": []}
{"num": 44, "husb_fid": "LWF8-N1V", "wife_fid": "LHRR-LWW", "husb_num": 126, "wife_num": 99, "fid": "MZHV-Z8Y", "marrdate": "18 Nov 1891", "marrplac": "Pittsburgh, Allegheny, Pennsylvania", "chil_fid": [], "chil_num": []}
{"num": 45, "husb_fid": "LYR1-P2V", "wife_fid": "LHRR-LWW", "husb_num": 127, "wife_num": 99, "fid": "MKJD-XZF", "marrdate": null, "marrplac": null, "chil_fid": [], "chil_num": []}
{"num": 46, "husb_fid": "LZT8-TDL", "wife_fid": "LHRR-LWW", "husb_num": 128, "wife_num": 99, "fid": "MKD6-QQB", "marrdate": null, "marrplac": null, "chil_fid": [], "chil_num": []}
{"num": 47, "husb_fid": "9VHB-NT4", "wife_fid": "LHRR-LWW", "husb_num": 129, "wife_num": 99, "fid": "MVN6-S11", "marrdate": null, "marrplac": null, "chil_fid": [], "chil_num": []}
{"num": 48, "husb_fid": "LR4T-VLN", "wife_fid": "LHRR-LWW", "husb_num": 130, "wife_num": 99, "fid": "MVZQ-71Z", "marrdate": null, "marrplac": null, "chil_fid": [], "chil_num": []}
{"num": 49, "husb_fid": "LTQX-K2P", "wife_fid": "LTQX-6CK", "husb_num": 131, "wife_num": 76, "fid": "MV2N-YC7", "marrdate": null, "marrplac": null, "chil_fid": [], "chil_num": []}
{"num": 50, "husb_fid": "MVFK-TQP", "wife_fid": "KGW2-2P4", "husb_num": 12, "wife_num": 132, "fid": "M29D-M72", "marrdate": null, "marrplac": null, "chil_fid": [], "chil_num": []}
{"num": 51, "husb_fid": "K6WT-NWT", "wife_fid": "KZ2X-SKM", "husb_num": 133, "wife_num": 54, "fid": "M3BY-KRV", "marrdate": "       1882", "marrplac": null, "chil_fid": [], "chil_num": []}
{"num": 52, "husb_fid": "LJ19-331", "wife_fid": "KP7V-FMM", "husb_num": 134, "wife_num": 49, "fid": "MFBH-F3Q", "marrdate": "19 January 1823", "marrplac": "Bruff, County Limerick, Ireland", "chil_fid": [], "chil_num": []}
{"num": 53, "husb_fid": "KLLY-TXP", "wife_fid": "KP7V-FMM", "husb_num": 135, "wife_num": 49, "fid": "M29Q-XRC", "marrdate": null, "marrplac": null, "chil_fid": [], "chil_num": []}
{"num": 54, "husb_fid": "LWLT-LFR", "wife_fid": "LWLT-LFL", "husb_num": 77, "wife_num": 136, "fid": "M8GP-WPL", "marrdate": "3 Feb 1901", "marrplac": "Cambridge, Middlesex, Massachusetts", "chil_fid": [], "chil_num": []}
{"num": 55, "husb_fid": "L23M-G3Q", "wife_fid": "L23M-LYV", "husb_num": 137, "wife_num": 48, "fid": "MNT7-LBW", "marrdate": null, "marrplac": null, "chil_fid": [], "chil_num": []}
{"num": 56, "husb_fid": "L89N-K62", "wife_fid": "9JK5-L2Y", "husb_num": 4, "wife_num": 138, "fid": "MKGR-R4S", "marrdate": null, "marrplac": null, "chil_fid": [], "chil_num": []}
{"num": 57, "husb_fid": "L89N-K62", "wife_fid": "KGWP-YKX", "husb_num": 4, "wife_num": 139, "fid": "MKGR-RJK", "marrdate": null, "marrplac": null, "chil_fid": [], "chil_num": []}
{"num": 58, "husb_fid": "LZNR-GY3", "wife_fid": "LVJ5-43Y", "husb_num": 35, "wife_num": 140, "fid": "MN4X-HRF", "marrdate": "29 Nov 1958", "marrplac": null, "chil_fid": [], "chil_num": []}
{"num": 59, "husb_fid": "LZNR-GY3", "wife_fid": "LLHG-514", "husb_num": 35, "wife_num": 141, "fid": "MJ64-Y6N", "marrdate": "1992", "marrplac": null, "chil_fid": [], "chil_num": []}
{"num": 60, "husb_fid": "L6YW-FK4", "wife_fid": "L6YW-X59", "husb_num": 142, "wife_num": 51, "fid": "MX6J-Q32", "marrdate": null, "marrplac": null, "chil_fid": [], "chil_num": []}
{"num": 61, "husb_fid": "LC2H-7NZ", "wife_fid": "LC26-1DD", "husb_num": 62, "wife_num": 143, "fid": "MQBB-47N", "marrdate": "       1887", "marrplac": ", Ontario, Canada", "chil_fid": [], "chil_num": []}
{"num": 62, "husb_fid": "K6MY-9V3", "wife_fid": "K6MQ-7TK", "husb_num": 144, "wife_num": 41, "fid": "M4VV-TSC", "marrdate": "12 OCT 1927", "marrplac": "Winthrop, Suffolk Co, MA", "chil_fid": [], "chil_num": []}
